import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const publicDir = fileURLToPath(new URL("../../public/", import.meta.url));

async function readPublic(name) {
  return readFile(join(publicDir, name), "utf8");
}

test("legacy navigation exposes wangzhuan and competitor remix entries", async () => {
  const index = await readPublic("index.html");
  const comic = await readPublic("comic.html");
  for (const html of [index, comic]) {
    assert.match(html, /href="\/wangzhuan\.html"/);
    assert.match(html, /href="\/competitor-remix\.html"/);
    assert.match(html, /网赚素材管线/);
    assert.match(html, /竞品素材改造/);
  }
});

test("wangzhuan page wires required API flows and states", async () => {
  const html = await readPublic("wangzhuan.html");
  const script = await readPublic("wangzhuan.js");
  const styles = await readPublic("styles.css");
  const common = await readPublic("wangzhuan-common.js");

  assert.match(html, /class="[^"]*\bwz-workbench\b/);
  assert.match(html, /class="[^"]*\bwz-canvas-toolbar\b/);
  assert.match(html, /class="[^"]*\bwz-canvas\b/);
  assert.match(html, /class="[^"]*\bwz-canvas-links\b/);
  assert.match(html, /class="[^"]*\bwz-node\b/);
  assert.match(html, /class="[^"]*\bwz-stepbar-item\b/);
  assert.match(html, /class="[^"]*\bwz-branches\b/);
  assert.match(html, /class="[^"]*\bwz-col-branches\b/);
  assert.match(html, /class="[^"]*\bwz-subflow\b/);
  assert.match(html, /class="[^"]*\bwz-primary-form\b/);
  assert.match(html, /autocomplete="off"/);
  assert.match(html, /class="[^"]*\bwz-advanced-settings\b/);
  assert.match(html, /id="wzStepbar"/);
  assert.match(html, /id="wzCanvas"/);
  assert.match(html, /id="wzCanvasLinks"/);
  assert.match(html, /id="wzBranches"/);
  assert.match(html, /data-node="upload"/);
  assert.match(html, /data-node="decompose"/);
  assert.match(html, /data-node="rewrite"/);
  assert.match(html, /data-node="batch"/);
  assert.match(html, /data-node="log"/);
  assert.match(html, /data-node="output"/);
  assert.match(html, /参考视频输入/);
  assert.match(html, /上传参考/);
  assert.match(html, /模型拆解/);
  assert.match(html, /产品改写/);
  assert.match(html, /可裂变 3\.1 \/ 3\.2 \/ 3\.3/);
  assert.match(html, /裂变子节点/);
  assert.match(html, /改写 3\.1/);
  assert.match(html, /产品信息/);
  assert.match(html, /本次投放/);
  assert.match(html, /<span class="wz-subno">3\.1\.1<\/span>[^<]*模板与批次默认值/);
  assert.match(html, /<span class="wz-subno">3\.1\.2<\/span>[^<]*产品信息/);
  assert.match(html, /<span class="wz-subno">3\.1\.3<\/span>[^<]*本次投放/);
  assert.match(html, /产品素材资产/);
  assert.match(html, /提示词配置/);
  assert.match(html, /AI 拆解脚本/);
  assert.match(html, /分析参考视频，提取镜头与脚本结构/);
  assert.match(html, /id="wzLlmServiceStatus"/);
  assert.match(html, /素材经验补充（可选）/);
  assert.match(html, /开始解析/);
  assert.match(html, /id="wzDecompositionForm"/);
  assert.match(html, /产品改写（可裂变/);
  assert.match(html, /批次参数/);
  assert.match(html, /生成批次/);
  assert.match(html, /结果与下载/);
  assert.match(html, /第 4 步子流程/);
  assert.match(html, /生成 Seedance 预案/);
  assert.match(html, /Seedance 2\.0/);
  assert.match(html, /id="wzLlmProvider"/);
  assert.match(html, /id="wzLlmModel"/);
  assert.match(html, /id="wzLlmEndpoint"/);
  assert.match(html, /https:\/\/skylink-gateway\.com\/api\/v1/);
  assert.match(html, /id="wzKnowledgeNotes"/);
  assert.match(html, /id="wzVariantPrompt"/);
  assert.match(html, /id="wzSeedanceModel"/);
  assert.match(html, /id="wzTemplateSelect"/);
  assert.match(html, /开发者选项（一般无需修改）/);
  assert.doesNotMatch(html, /LLM endpoint/);
  assert.match(html, /参考视频/);
  assert.match(html, /运行日志/);
  assert.doesNotMatch(html, /ffprobe/);
  assert.doesNotMatch(html, /GPT JSON 拆解/);
  assert.doesNotMatch(html, /Seedance Prompt/);
  assert.doesNotMatch(html, /id="wzReferenceDuration"/);
  assert.doesNotMatch(html, /id="wzReferenceWidth"/);
  assert.doesNotMatch(html, /id="wzReferenceHeight"/);
  assert.match(html, /id="wzProductLink"/);
  assert.match(html, /id="wzProductIconFile"/);
  assert.match(html, /id="wzProductScreenshotFile"/);
  assert.match(html, /id="wzProductRecordingFile"/);
  assert.match(html, /id="wzEndingAssetFile"/);
  assert.match(html, /id="wzPersonAssetFile"/);
  assert.match(html, /id="wzRewardElementFile"/);
  assert.match(html, /id="wzMaterialDirection"/);
  assert.match(html, /id="wzVoiceoverStyle"/);
  assert.match(html, /id="wzCustomPrompt"/);
  assert.match(html, /id="wzNegativePrompt"/);
  assert.match(html, /id="wzReferenceFile"/);
  assert.match(html, />上传视频</);
  assert.match(html, /id="wzEstimateBtn"/);
  assert.match(html, /id="wzDownloadBtn"/);
  assert.match(html, /id="wzActiveLockActions"/);
  assert.match(html, /id="wzGlobalError"/);
  assert.doesNotMatch(html, /id="wzStopActiveLockBtn"/);
  assert.doesNotMatch(html, /id="wzTaskSpaceBtn"/);
  assert.match(html, /topbar-account-link.*任务管理/);
  assert.doesNotMatch(html, /platform-nav-item[^>]*href="\/wangzhuan-tasks\.html"/);
  const uploadNode = html.match(/<section class="[^"]*\bwz-node\b[^"]*" id="wzNodeUpload"[\s\S]*?<\/section>/)?.[0] || "";
  assert.match(uploadNode, /参考视频输入/);
  assert.doesNotMatch(uploadNode, /id="wzProductName"/);
  assert.doesNotMatch(uploadNode, /id="wzProductIconFile"/);
  assert.doesNotMatch(uploadNode, /id="wzBatchName"/);
  assert.match(script, /productLink/);
  assert.match(script, /assetFileNames/);
  assert.match(script, /llmConfig/);
  assert.match(script, /llmEndpoint/);
  assert.match(script, /function resetTransientFormState/);
  assert.match(script, /resetTransientFormState\(\);\s*\n\s*renderTruthFields/);
  assert.match(script, /loadLlmConfig/);
  assert.match(script, /renderLlmServiceStatus/);
  assert.match(script, /AI 拆解服务已就绪/);
  assert.match(script, /\/api\/wangzhuan\/llm-config/);
  assert.match(script, /gpt-5\.4/);
  assert.match(script, /解析未完成：/);
  assert.match(script, /knowledgeNotes/);
  assert.match(script, /variantPrompt/);
  assert.match(script, /seedanceModel/);
  assert.match(script, /materialDirection/);
  assert.match(script, /customPrompt/);
  assert.match(script, /negativePrompt/);
  assert.match(script, /wz-rule-row/);
  assert.match(script, /不是账号权限/);
  assert.match(styles, /\.wz-rule-row/);
  assert.match(styles, /\.wz-rule-groups/);
  assert.match(styles, /\.wz-canvas-toolbar/);
  assert.match(styles, /\.wz-canvas/);
  assert.match(styles, /\.wz-canvas-links/);
  assert.match(styles, /\.wz-node/);
  assert.match(styles, /\.wz-stepbar/);
  assert.match(styles, /\.wz-branches/);
  assert.match(styles, /\.wz-col-branches/);
  assert.match(styles, /\.wz-primary-form/);
  assert.match(styles, /\.wz-advanced-settings/);
  assert.match(script, /\/api\/wangzhuan\/templates/);
  assert.match(script, /copyFromVersionId:\s*state\.selectedTemplate\.versionId/);
  assert.match(script, /selectedTemplateNameChanged/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/check/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/draft-decomposition/);
  assert.match(script, /draftReferenceVideoDecomposition/);
  assert.match(script, /file_required/);
  assert.match(script, /请选择一个真实参考视频文件，系统会读取时长、画幅和音轨信息/);
  assert.match(script, /读取视频信息/);
  assert.match(script, /估算本批任务/);
  assert.match(script, /ESTIMATE_BTN_LABEL/);
  assert.match(script, /syncEstimateButtonLabel/);
  assert.match(html, /id="wzEstimateBtn"/);
  assert.doesNotMatch(html, /id="wzEstimateBtn"[^>]*>重新估算</);
  assert.doesNotMatch(script, /tinyVideoDataUrl\("reference"\)/);
  assert.doesNotMatch(script, /sample-reference\.mp4/);
  assert.match(script, /画幅/);
  assert.match(script, /码率/);
  assert.match(script, /音轨/);
  assert.doesNotMatch(script, /durationSec: Number\(els\.referenceDuration\.value\)/);
  assert.doesNotMatch(script, /width: Number\(els\.referenceWidth\.value\)/);
  assert.doesNotMatch(script, /height: Number\(els\.referenceHeight\.value\)/);
  assert.doesNotMatch(script, /canExtractFrame: true/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/decompose/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/\$\{encodeURIComponent\(referenceVideoId\)\}\/workflow-state/);
  assert.match(script, /restoreWorkflowSession/);
  assert.match(script, /renderBatchReadiness/);
  assert.match(script, /WORKFLOW_SESSION_KEY/);
  assert.match(script, /再次保存将写入新版本/);
  assert.match(html, /id="wzBatchReadiness"/);
  assert.match(html, /保存模板.*全部 3\.x/);
  assert.match(styles, /\.wz-batch-readiness/);
  assert.match(script, /wzFocusNodeId/);
  assert.match(script, /window\.wzFocusNode/);
  assert.match(styles, /\.wz-focus-mode/);
  assert.match(script, /\/api\/wangzhuan\/batches\/estimate/);
  assert.match(script, /\/api\/wangzhuan\/batches\/plan/);
  assert.match(script, /confirmBatchPlanRequest/);
  assert.doesNotMatch(script, /\/api\/wangzhuan\/batches\/start/);
  assert.match(html, /id="wzPlanBatchBtn"/);
  assert.match(html, /id="wzConfirmPlanBtn"/);
  assert.match(html, /id="wzPlanBox"/);
  assert.match(html, /生成 Seedance 预案/);
  assert.match(html, /wz-batch-steps/);
  assert.match(html, /估算结果/);
  assert.doesNotMatch(html, /生成第4步预案/);
  assert.match(html, /确认预案并生成视频/);
  assert.doesNotMatch(html, /id="wzStartBatchBtn"/);
  assert.match(script, /wangzhuan-task-nav\.js/);
  assert.match(script, /showActiveLockFromError/);
  assert.match(common, /taskSpaceHref/);
  assert.match(common, /wangzhuan-tasks\.html/);
  assert.match(common, /打开任务管理/);
  assert.match(common, /confirmBatchPlanRequest/);
  assert.match(script, /confirmBatchPlanRequest/);
  assert.match(script, /collectEditablePlans/);
  assert.match(script, /data-plan-field="seedancePrompt"/);
  assert.match(script, /wz-plan-editor/);
  assert.match(script, /renderOutputPreview/);
  assert.match(script, /<video src="\$\{safeUrl\}" controls preload="metadata" playsinline><\/video>/);
  assert.match(common, /plans:\s*plans\.map/);
  assert.match(script, /galleryPageSize:\s*20/);
  assert.match(script, /pageSize:\s*String\(state\.galleryPageSize\)/);
  assert.match(script, /sourceType:\s*"pipeline"/);
  assert.doesNotMatch(script, /query\.set\("batchId"/);
  assert.match(script, /data-gallery-page/);
  assert.match(styles, /\.wz-gallery-pager/);
  assert.match(styles, /\.wz-lock-actions/);
  assert.match(common, /payload\.code !== "ok"/);
  assert.match(common, /requestId/);
});

test("competitor remix page keeps independent video-platform remix flow", async () => {
  const html = await readPublic("competitor-remix.html");
  const script = await readPublic("competitor-remix.js");
  const styles = await readPublic("styles.css");

  assert.match(html, /class="[^"]*\bwz-workbench\b/);
  assert.match(html, /autocomplete="off"/);
  assert.match(html, /id="remixStepbar"/);
  assert.match(html, /id="remixCanvas"/);
  assert.match(html, /id="remixCanvasLinks"/);
  assert.match(html, /data-node="source"/);
  assert.match(html, /data-node="mask"/);
  assert.match(html, /data-node="mask-preview"/);
  assert.match(html, /data-node="delivery"/);
  assert.match(html, /data-node="gallery"/);
  assert.match(html, /源素材输入/);
  assert.match(html, /区域与能力/);
  assert.match(html, /预览与交付/);
  assert.match(html, /Mask 区域预览/);
  assert.match(html, /id="remixMaskConfirmBtn"/);
  assert.match(html, /Mask 编辑窗口/);
  assert.match(html, /id="remixMaskEditor"/);
  assert.match(html, /id="remixMaskMediaLayer"/);
  assert.match(html, /id="remixMaskLayer"/);
  assert.match(html, /id="remixMaskPreviewCanvas"/);
  assert.match(html, /id="remixPrototypeSourceList"/);
  assert.match(html, /id="remixPrototypeReviewOnly"/);
  assert.match(html, /id="remixPrototypeApplyRegionsBtn"/);
  assert.match(html, /id="remixPrototypeConfirmReviewBtn"/);
  assert.match(html, /id="remixPrototypeCapabilityPlan"/);
  assert.match(html, /id="remixPrototypeTaskQueue"/);
  assert.match(html, /id="remixPrototypeGallery"/);
  assert.match(html, /批量素材/);
  assert.match(html, /单素材可视化编辑/);
  assert.match(html, /异步任务队列/);
  assert.match(html, /只看需复核/);
  assert.match(html, /应用当前区域到选中素材/);
  assert.match(html, /生成草稿任务/);
  assert.match(html, /模拟推进/);
  assert.match(html, /上传源素材后框选多个区域/);
  assert.match(html, /视频处理平台 ai_remove/);
  assert.doesNotMatch(html, /id="remixDuration"/);
  assert.doesNotMatch(html, /id="remixWidth"/);
  assert.doesNotMatch(html, /id="remixHeight"/);
  assert.doesNotMatch(html, /改造参数/);
  assert.doesNotMatch(html, /添加区域/);
  assert.doesNotMatch(html, /id="remixRegionsBox"/);
  assert.doesNotMatch(html, /能力估算/);
  assert.doesNotMatch(html, /id="remixEstimateBtn"/);
  assert.doesNotMatch(html, /id="remixStartBtn"/);
  assert.doesNotMatch(html, /AI 拆解配置/);
  assert.doesNotMatch(html, /视频脚本拆解/);
  assert.match(html, /href="\/wangzhuan\.html"/);
  assert.match(html, /id="remixConfirmBtn"/);
  assert.match(html, /id="remixDownloadBtn"/);
  assert.match(script, /\/api\/wangzhuan\/remix\/upload/);
  assert.match(script, /\/api\/wangzhuan\/remix\/active/);
  assert.match(script, /function resetBrowserRestoredInputs/);
  assert.match(script, /resetBrowserRestoredInputs\(\);\s*\n\s*renderMaskEditor/);
  assert.match(script, /loadActiveRemix/);
  assert.match(script, /\/api\/wangzhuan\/remix\/mask-edit/);
  assert.match(script, /prototype:\s*\{/);
  assert.match(script, /function createMockSourceFromFile/);
  assert.match(script, /function activePrototypeSource/);
  assert.match(script, /function renderPrototypeSources/);
  assert.match(script, /function renderPrototypeCapabilityPlan/);
  assert.match(script, /function renderPrototypeTaskQueue/);
  assert.match(script, /function generatePrototypeDraftTasks/);
  assert.match(script, /function advancePrototypeTask/);
  assert.match(script, /function copyRegionsToSelectedPrototypeSources/);
  assert.match(script, /function confirmPrototypeSourceReview/);
  assert.match(script, /const PROTOTYPE_MODE = true/);
  assert.doesNotMatch(script, /startMaskEdit\(\);\s*\/\/ prototype submit/);
  assert.doesNotMatch(script, /\/api\/wangzhuan\/remix\/estimate/);
  assert.doesNotMatch(script, /durationSec: Number\(els\.sourceDuration\.value\)/);
  assert.doesNotMatch(script, /width: Number\(els\.sourceWidth\.value\)/);
  assert.doesNotMatch(script, /height: Number\(els\.sourceHeight\.value\)/);
  assert.match(script, /远端 Job/);
  assert.match(script, /远端状态/);
  assert.match(script, /renderSourcePreview/);
  assert.match(script, /remix-source-preview/);
  assert.match(script, /style="--remix-media-aspect-ratio:\s*\$\{escapeHtml\(mediaAspectRatioValue\(mediaDimensionsFromProbe\(probe\)\)\)\}"/);
  assert.match(script, /<video src="\$\{safeUrl\}" controls preload="metadata" playsinline><\/video>/);
  assert.match(script, /<img src="\$\{safeUrl\}" alt="源素材预览" \/>/);
  assert.match(script, /bindMaskEditor/);
  assert.match(script, /pointerdown/);
  assert.match(script, /pointermove/);
  assert.match(script, /pointerup/);
  assert.match(script, /data-resize-handle/);
  assert.match(script, /commitMaskEdit/);
  assert.match(script, /renderMaskPreview/);
  assert.match(script, /maskPreviewDataUrl/);
  assert.match(script, /actualMediaCache/);
  assert.match(script, /rememberActualMediaDimensions/);
  assert.match(script, /actualMediaDimensions/);
  assert.match(script, /videoWidth/);
  assert.match(script, /mediaViewport/);
  assert.match(script, /syncMaskLayerViewport/);
  assert.match(script, /renderMaskMedia\(true\)/);
  assert.match(script, /dataset\.sourceId === state\.source\.sourceId/);
  assert.match(script, /--remix-media-aspect-ratio/);
  assert.match(styles, /\.remix-mask-editor/);
  assert.match(styles, /\.remix-source-preview[\s\S]*?aspect-ratio:\s*var\(--remix-media-aspect-ratio,\s*9 \/ 16\)/);
  assert.match(styles, /\.remix-mask-media/);
  assert.match(styles, /\.remix-mask-layer/);
  assert.match(styles, /\.remix-mask-preview/);
  assert.match(styles, /--remix-media-aspect-ratio/);
  assert.match(styles, /\.wz-region-rect\.selected/);
  assert.match(styles, /\.remix-prototype-source-card/);
  assert.match(styles, /\.remix-prototype-source-card\.active/);
  assert.match(styles, /\.remix-prototype-task/);
  assert.match(styles, /\.remix-prototype-task\.failed/);
  assert.match(styles, /\.remix-prototype-capability-grid/);
  assert.match(styles, /\.remix-prototype-toolbar/);
  assert.match(styles, /\.remix-prototype-output-grid/);
  assert.match(script, /preview-confirm/);
  assert.match(script, /unsupported_capability/);
  assert.match(script, /downloadZip/);
  assert.match(script, /galleryPageSize:\s*20/);
  assert.match(script, /pageSize:\s*String\(state\.galleryPageSize\)/);
  assert.match(script, /sourceType:\s*"remix"/);
  assert.doesNotMatch(script, /query\.set\("remixId"/);
  assert.match(script, /data-gallery-page/);
  assert.match(styles, /\.wz-gallery-pager/);
  assert.match(script, /POLL_INTERVAL_MS/);
  assert.doesNotMatch(script, /attempts\s*>=\s*8/);
  assert.match(script, /wangzhuan-task-nav\.js/);
  assert.doesNotMatch(html, /id="remixTaskSpaceBtn"/);
});

test("task management page exposes dedicated task space", async () => {
  const html = await readPublic("wangzhuan-tasks.html");
  const script = await readPublic("wangzhuan-tasks.js");
  const styles = await readPublic("styles.css");

  assert.match(html, /任务管理/);
  assert.match(html, /topbar-account-link active.*wangzhuan-tasks\.html/);
  assert.doesNotMatch(html, /platform-nav-item[^>]*href="\/wangzhuan-tasks\.html"/);
  assert.match(html, /id="wzTasksList"/);
  assert.match(html, /id="wzTasksDetail"/);
  assert.match(html, /wzTasksTypePipeline/);
  assert.match(html, /网赚素材管线/);
  assert.match(html, /竞品素材改造/);
  assert.match(script, /\/api\/wangzhuan\/tasks/);
  assert.match(script, /renderTaskMediaCompare/);
  assert.match(script, /pickPrimaryOutput/);
  assert.match(script, /runType/);
  assert.match(script, /confirmBatchPlan/);
  assert.match(script, /wzTasksRunQcBtn/);
  assert.match(script, /运行视频质检/);
  assert.match(script, /\/api\/wangzhuan\/batches\/\$\{encodeURIComponent\(batch\.batchId\)\}\/qc/);
  assert.match(script, /batch\.status === "qc" \? "放弃批次" : "停止任务"/);
  assert.match(script, /workbenchHref/);
  assert.match(styles, /\.wz-tasks-layout/);
  assert.match(styles, /\.wz-tasks-media-stage/);
  assert.match(styles, /\.wz-tasks-type-badge/);
});

test("wangzhuan confirmation keeps saved decomposition state clear", async () => {
  const script = await readPublic("wangzhuan.js");
  const html = await readPublic("wangzhuan.html");

  assert.match(script, /function isDecompositionConfirmed/);
  assert.match(script, /脚本拆解已确认，请继续填写第三步产品改写/);
  assert.match(script, /TEMPLATE_SAVED_MESSAGE/);
  assert.match(script, /isTemplateCommitted/);
  assert.match(script, /setTemplateFormLocked/);
  assert.match(script, /focusBatchStep\(\)/);
  assert.match(html, /id="wzTemplateStatus"/);
  assert.match(script, /function syncDecompositionControls/);
  assert.match(script, /flattenDecompositionFieldValue/);
  assert.match(script, /fitDecompositionTextareas/);
  assert.match(script, /wz-decomposition-input/);
  assert.match(script, /开始解析/);
  assert.match(script, /重新解析/);
  assert.doesNotMatch(script, /wzDecompositionText/);
  assert.doesNotMatch(script, /els\.decomposeBtn\.disabled = isDecompositionConfirmed\(\) \|\| !els\.decompositionText\.value\.trim\(\)/);
});

test("wangzhuan branch nodes are collected and persisted as editable drafts", async () => {
  const script = await readPublic("wangzhuan.js");
  const canvas = await readPublic("wz-canvas.js");

  assert.match(script, /function collectBranchDrafts/);
  assert.match(script, /function applyBranches/);
  assert.match(script, /branches: collectBranchDrafts\(\)/);
  assert.match(script, /branchId/);
  assert.match(script, /branchLabel/);
  assert.match(script, /assetUrls/);
  assert.match(script, /assetStorageKeys/);
  assert.match(script, /await uploadBranchAssets\(\)/);
  assert.match(script, /templateSnapshot/);
  assert.match(script, /branchCount/);
  assert.match(canvas, /window\.wzCreateBranchNode/);
  assert.match(canvas, /wz-save-branch/);
  assert.doesNotMatch(canvas, /后端多分支接口就绪后/);
  assert.doesNotMatch(canvas, /Strip identity from the clone so it can't break ID-based business JS/);
});

test("wangzhuan generation progress exposes upstream task visibility", async () => {
  const common = await readPublic("wangzhuan-common.js");
  const script = await readPublic("wangzhuan.js");
  const styles = await readPublic("styles.css");

  assert.match(common, /export function isBatchGenerationActive/);
  assert.match(common, /export function renderGenerationTaskCards/);
  assert.match(common, /export function formatWorkflowEvent/);
  assert.match(script, /renderGenerationTaskCards\(tasks\)/);
  assert.match(script, /formatWorkflowEvent\(event\)/);
  assert.match(script, /isBatchGenerationActive\(batch, tasks\)/);
  assert.match(styles, /\.wz-generation-panel/);
});

test("wangzhuan batch qc state distinguishes generation done from qc running", async () => {
  const common = await readPublic("wangzhuan-common.js");
  const script = await readPublic("wangzhuan.js");

  assert.match(common, /export function batchStatusDisplayLabel/);
  assert.match(common, /export function batchGenerationProgress/);
  assert.match(common, /export function isBatchQcRunnable/);
  assert.match(common, /downloaded: "已下载"/);
  assert.match(common, /qc: "待质检"/);
  assert.match(script, /isBatchQcRunnable\(batch, tasks, outputs\)/);
  assert.match(script, /function isQcBatchPending/);
  assert.match(script, /当前批次已生成完成，请先运行视频质检或放弃批次/);
  assert.match(script, /els\.estimateBtn\) els\.estimateBtn\.disabled = isQcBatchPending\(batch\)/);
  assert.match(script, /isQcBatchPending\(batch\) \? "放弃批次" : "停止任务"/);
  assert.match(script, /omni_reference/);
});

test("wangzhuan keeps step 4 focused until seedance plan is confirmed", async () => {
  const script = await readPublic("wangzhuan.js");
  const canvas = await readPublic("wz-canvas.js");

  assert.match(script, /syncBatchNodeStatus/);
  assert.match(script, /dataset\.batchStatus/);
  assert.match(script, /focusBatchStep\(\);\s*\n\s*showToast\("Seedance 预案已生成/);
  assert.match(script, /focusLogStep\(\);\s*\n\s*showToast\("批次已提交 Seedance 生成/);
  assert.match(canvas, /status === "preview_required"\) return false/);
  assert.match(canvas, /data-batch-status/);
});

test("competitor remix locks submit controls while a task is active", async () => {
  const script = await readPublic("competitor-remix.js");

  assert.match(script, /function isActiveRemixStatus/);
  assert.match(script, /function isSourceSubmitLocked/);
  assert.match(script, /function resetWorkshopState/);
  assert.match(script, /resetWorkshopState\(\)/);
  assert.match(script, /bindPageLifecycle/);
  assert.match(script, /addEventListener\("pageshow"/);
  assert.match(script, /state\.detail = \{ remix: \{ status: "queued"/);
  assert.match(script, /const active = isActiveRemixStatus\(remix\.status\)/);
  assert.match(script, /const unavailable = state\.initFailed/);
  assert.match(script, /els\.maskConfirmBtn\.disabled = unavailable \|\| state\.submitBlocked \|\| submitLocked \|\| !state\.source \|\| !state\.regions\.length/);
  assert.match(script, /els\.uploadBtn\.disabled = unavailable \|\| activeRemix/);
  assert.match(script, /els\.clearMaskBtn\.disabled = unavailable \|\| activeRemix/);
  assert.match(script, /该素材已完成改造，不可重复提交/);
  assert.match(script, /处理中，请等待状态刷新后再继续操作/);
});

test("competitor remix disables writes when initialization fails", async () => {
  const script = await readPublic("competitor-remix.js");

  assert.match(script, /initFailed: false/);
  assert.match(script, /function handleInitialDataError/);
  assert.match(script, /state\.initFailed = true/);
  assert.match(script, /页面初始化失败，请修复 MySQL 连接后刷新/);
});

test("release packaging excludes exported environment dumps", async () => {
  const gitignore = await readFile(join(publicDir, "../.gitignore"), "utf8");
  const dockerignore = await readFile(join(publicDir, "../.dockerignore"), "utf8");
  const releaseScript = await readFile(join(publicDir, "../package-release.ps1"), "utf8");

  assert.match(gitignore, /^env\.export\.txt$/m);
  assert.match(dockerignore, /^env\.export\.txt$/m);
  assert.match(releaseScript, /env\.export\.txt/);
});
