import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const publicDir = fileURLToPath(new URL("../../public/", import.meta.url));

async function readPublic(name) {
  return readFile(join(publicDir, name), "utf8");
}

test("legacy navigation exposes wangzhuan and competitor remix entries", async () => {
  const index = await readPublic("index.html");
  const comic = await readPublic("comic.html");
  for (const html of [index, comic]) {
    assert.match(html, /href="\/wangzhuan\.html"/);
    assert.match(html, /href="\/competitor-remix\.html"/);
    assert.match(html, /网赚素材管线/);
    assert.match(html, /竞品素材改造/);
  }
});

test("wangzhuan page wires required API flows and states", async () => {
  const html = await readPublic("wangzhuan.html");
  const script = await readPublic("wangzhuan.js");
  const styles = await readPublic("styles.css");
  const common = await readPublic("wangzhuan-common.js");

  assert.match(html, /class="[^"]*\bwz-workbench\b/);
  assert.match(html, /class="[^"]*\bwz-business-shell\b/);
  assert.match(html, /class="[^"]*\bwz-business-summary\b/);
  assert.match(html, /class="[^"]*\bwz-graph-toolbar\b/);
  assert.match(html, /class="[^"]*\bwz-node-canvas\b/);
  assert.match(html, /class="[^"]*\bwz-graph-links\b/);
  assert.match(html, /class="[^"]*\bwz-node-card\b/);
  assert.match(html, /class="[^"]*\bwz-stepper\b/);
  assert.match(html, /class="[^"]*\bwz-primary-form\b/);
  assert.match(html, /class="[^"]*\bwz-advanced-settings\b/);
  assert.match(html, /业务模式控制台/);
  assert.match(html, /按固定管线跑素材/);
  assert.match(html, /固定管线工作台/);
  assert.match(html, /选模板、传参考视频、确认批次即可跑完整素材生成流程/);
  assert.match(html, /普通用户模式/);
  assert.match(html, /选模板、传参考视频、确认批次即可跑完整管线/);
  assert.match(html, /固定管线/);
  assert.match(html, /少量必填/);
  assert.match(html, /常用参数/);
  assert.match(html, /低频设置/);
  assert.match(html, /id="wz-left-rail"/);
  assert.match(html, /id="wz-main-flow"/);
  assert.match(html, /id="wz-right-rail"/);
  assert.match(html, /data-flow-step="reference-assets"/);
  assert.match(html, /data-flow-step="knowledge-script"/);
  assert.match(html, /data-flow-step="seedance-delivery"/);
  assert.match(html, /参考视频输入/);
  assert.match(html, /知识库沉淀与脚本拆解/);
  assert.match(html, /产品改写/);
  assert.match(html, /提交生成/);
  assert.match(html, /参考视频进入后，系统读取信息并交给模型拆解/);
  assert.match(html, /拆解与改写/);
  assert.match(html, /把视频拆成 JSON 脚本，再套入我方产品和渠道规则/);
  assert.match(html, /GPT 拆解脚本/);
  assert.match(html, /按 JSON 格式拆分脚本/);
  assert.match(html, /自动拆解参考视频/);
  assert.match(html, /生成后再确认保存/);
  assert.match(html, /结合产品改写并裂变/);
  assert.match(html, /生成批次/);
  assert.match(html, /结果与下载/);
  assert.match(html, /Seedance 2\.0/);
  assert.match(html, /id="wzLlmProvider"/);
  assert.match(html, /id="wzLlmModel"/);
  assert.match(html, /id="wzLlmEndpoint"/);
  assert.match(html, /https:\/\/skylink-gateway\.com\/api\/v1/);
  assert.match(html, /id="wzKnowledgeNotes"/);
  assert.match(html, /id="wzVariantPrompt"/);
  assert.match(html, /id="wzSeedanceModel"/);
  assert.match(html, /id="wzTemplateSelect"/);
  assert.match(html, /模型接口配置/);
  assert.match(html, /参考视频/);
  assert.match(html, /运行日志/);
  assert.doesNotMatch(html, /ffprobe/);
  assert.doesNotMatch(html, /GPT JSON 拆解/);
  assert.doesNotMatch(html, /Seedance Prompt/);
  assert.doesNotMatch(html, /id="wzReferenceDuration"/);
  assert.doesNotMatch(html, /id="wzReferenceWidth"/);
  assert.doesNotMatch(html, /id="wzReferenceHeight"/);
  assert.match(html, /id="wzProductLink"/);
  assert.match(html, /id="wzProductIconFile"/);
  assert.match(html, /id="wzProductScreenshotFile"/);
  assert.match(html, /id="wzProductRecordingFile"/);
  assert.match(html, /id="wzEndingAssetFile"/);
  assert.match(html, /id="wzPersonAssetFile"/);
  assert.match(html, /id="wzRewardElementFile"/);
  assert.match(html, /id="wzMaterialDirection"/);
  assert.match(html, /id="wzVoiceoverStyle"/);
  assert.match(html, /id="wzCustomPrompt"/);
  assert.match(html, /id="wzNegativePrompt"/);
  assert.match(html, /id="wzReferenceFile"/);
  assert.match(html, />上传视频</);
  assert.match(html, /id="wzEstimateBtn"/);
  assert.match(html, /id="wzDownloadBtn"/);
  assert.match(html, /id="wzActiveLockActions"/);
  assert.match(html, /id="wzStopActiveLockBtn"/);
  const leftRail = html.match(/<section id="wz-left-rail"[\s\S]*?<\/section>\s*<section id="wz-main-flow"/)?.[0] || "";
  assert.match(leftRail, /参考视频输入/);
  assert.doesNotMatch(leftRail, /id="wzProductName"/);
  assert.doesNotMatch(leftRail, /id="wzProductIconFile"/);
  assert.doesNotMatch(leftRail, /id="wzBatchName"/);
  assert.match(script, /productLink/);
  assert.match(script, /assetFileNames/);
  assert.match(script, /llmConfig/);
  assert.match(script, /llmEndpoint/);
  assert.match(script, /loadLlmConfig/);
  assert.match(script, /\/api\/wangzhuan\/llm-config/);
  assert.match(script, /gpt-5\.4/);
  assert.match(script, /模型拆解未完成：/);
  assert.match(script, /knowledgeNotes/);
  assert.match(script, /variantPrompt/);
  assert.match(script, /seedanceModel/);
  assert.match(script, /materialDirection/);
  assert.match(script, /customPrompt/);
  assert.match(script, /negativePrompt/);
  assert.match(script, /wz-rule-row/);
  assert.match(script, /不是账号权限/);
  assert.match(styles, /\.wz-rule-row/);
  assert.match(styles, /\.wz-rule-groups/);
  assert.match(styles, /\.wz-business-shell/);
  assert.match(styles, /\.wz-business-summary/);
  assert.match(styles, /\.wz-graph-toolbar/);
  assert.match(styles, /\.wz-node-canvas/);
  assert.match(styles, /\.wz-graph-links/);
  assert.match(styles, /\.wz-node-card/);
  assert.match(styles, /\.wz-stepper/);
  assert.match(styles, /\.wz-primary-form/);
  assert.match(styles, /\.wz-advanced-settings/);
  assert.match(script, /\/api\/wangzhuan\/templates/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/check/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/draft-decomposition/);
  assert.match(script, /draftReferenceVideoDecomposition/);
  assert.match(script, /file_required/);
  assert.match(script, /请选择一个真实参考视频文件，系统会读取时长、画幅和音轨信息/);
  assert.match(script, /读取视频信息/);
  assert.match(script, /脚本拆解已确认，可以继续估算生成批次/);
  assert.doesNotMatch(script, /tinyVideoDataUrl\("reference"\)/);
  assert.doesNotMatch(script, /sample-reference\.mp4/);
  assert.match(script, /画幅/);
  assert.match(script, /码率/);
  assert.match(script, /音轨/);
  assert.doesNotMatch(script, /durationSec: Number\(els\.referenceDuration\.value\)/);
  assert.doesNotMatch(script, /width: Number\(els\.referenceWidth\.value\)/);
  assert.doesNotMatch(script, /height: Number\(els\.referenceHeight\.value\)/);
  assert.doesNotMatch(script, /canExtractFrame: true/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/decompose/);
  assert.match(script, /\/api\/wangzhuan\/batches\/estimate/);
  assert.match(script, /\/api\/wangzhuan\/batches\/start/);
  assert.match(script, /activeLockFromError/);
  assert.match(script, /\/api\/wangzhuan\/remix\/\$\{encodeURIComponent\(lock\.id\)\}\/stop/);
  assert.match(script, /frontend_stop_active_lock/);
  assert.match(styles, /\.wz-lock-actions/);
  assert.match(common, /payload\.code !== "ok"/);
  assert.match(common, /requestId/);
});

test("competitor remix page keeps independent video-platform remix flow", async () => {
  const html = await readPublic("competitor-remix.html");
  const script = await readPublic("competitor-remix.js");
  const styles = await readPublic("styles.css");

  assert.match(html, /class="[^"]*\bwz-workbench\b/);
  assert.match(html, /id="remix-left-rail"/);
  assert.match(html, /id="remix-main-flow"/);
  assert.match(html, /id="remix-right-rail"/);
  assert.match(html, /data-flow-step="source-assets"/);
  assert.match(html, /data-flow-step="region-rules"/);
  assert.match(html, /data-flow-step="preview-delivery"/);
  assert.match(html, /源素材输入/);
  assert.match(html, /区域与能力/);
  assert.match(html, /预览与交付/);
  assert.match(html, /Mask 区域预览/);
  assert.match(html, /id="remixMaskConfirmBtn"/);
  assert.match(html, /Mask 编辑窗口/);
  assert.match(html, /id="remixMaskEditor"/);
  assert.match(html, /id="remixMaskMediaLayer"/);
  assert.match(html, /id="remixMaskLayer"/);
  assert.match(html, /id="remixMaskPreviewCanvas"/);
  assert.match(html, /上传源素材后框选多个区域/);
  assert.match(html, /视频处理平台 ai_remove/);
  assert.doesNotMatch(html, /id="remixDuration"/);
  assert.doesNotMatch(html, /id="remixWidth"/);
  assert.doesNotMatch(html, /id="remixHeight"/);
  assert.doesNotMatch(html, /改造参数/);
  assert.doesNotMatch(html, /添加区域/);
  assert.doesNotMatch(html, /id="remixRegionsBox"/);
  assert.doesNotMatch(html, /能力估算/);
  assert.doesNotMatch(html, /id="remixEstimateBtn"/);
  assert.doesNotMatch(html, /id="remixStartBtn"/);
  assert.doesNotMatch(html, /AI 拆解配置/);
  assert.doesNotMatch(html, /视频脚本拆解/);
  assert.match(html, /href="\/wangzhuan\.html"/);
  assert.match(html, /id="remixConfirmBtn"/);
  assert.match(html, /id="remixDownloadBtn"/);
  assert.match(script, /\/api\/wangzhuan\/remix\/upload/);
  assert.match(script, /\/api\/wangzhuan\/remix\/mask-edit/);
  assert.doesNotMatch(script, /\/api\/wangzhuan\/remix\/estimate/);
  assert.doesNotMatch(script, /durationSec: Number\(els\.sourceDuration\.value\)/);
  assert.doesNotMatch(script, /width: Number\(els\.sourceWidth\.value\)/);
  assert.doesNotMatch(script, /height: Number\(els\.sourceHeight\.value\)/);
  assert.match(script, /远端 Job/);
  assert.match(script, /远端状态/);
  assert.match(script, /renderSourcePreview/);
  assert.match(script, /remix-source-preview/);
  assert.match(script, /style="--remix-media-aspect-ratio:\s*\$\{escapeHtml\(mediaAspectRatioValue\(mediaDimensionsFromProbe\(probe\)\)\)\}"/);
  assert.match(script, /<video src="\$\{safeUrl\}" controls preload="metadata" playsinline><\/video>/);
  assert.match(script, /<img src="\$\{safeUrl\}" alt="源素材预览" \/>/);
  assert.match(script, /bindMaskEditor/);
  assert.match(script, /pointerdown/);
  assert.match(script, /pointermove/);
  assert.match(script, /pointerup/);
  assert.match(script, /data-resize-handle/);
  assert.match(script, /commitMaskEdit/);
  assert.match(script, /renderMaskPreview/);
  assert.match(script, /maskPreviewDataUrl/);
  assert.match(script, /actualMediaCache/);
  assert.match(script, /rememberActualMediaDimensions/);
  assert.match(script, /actualMediaDimensions/);
  assert.match(script, /videoWidth/);
  assert.match(script, /mediaViewport/);
  assert.match(script, /syncMaskLayerViewport/);
  assert.match(script, /renderMaskMedia\(true\)/);
  assert.match(script, /dataset\.sourceId === state\.source\.sourceId/);
  assert.match(script, /--remix-media-aspect-ratio/);
  assert.match(styles, /\.remix-mask-editor/);
  assert.match(styles, /\.remix-source-preview[\s\S]*?aspect-ratio:\s*var\(--remix-media-aspect-ratio,\s*9 \/ 16\)/);
  assert.match(styles, /\.remix-mask-media/);
  assert.match(styles, /\.remix-mask-layer/);
  assert.match(styles, /\.remix-mask-preview/);
  assert.match(styles, /--remix-media-aspect-ratio/);
  assert.match(styles, /\.wz-region-rect\.selected/);
  assert.match(script, /preview-confirm/);
  assert.match(script, /unsupported_capability/);
  assert.match(script, /downloadZip/);
  assert.match(script, /POLL_INTERVAL_MS/);
  assert.doesNotMatch(script, /attempts\s*>=\s*8/);
});

test("competitor remix locks submit controls while a task is active", async () => {
  const script = await readPublic("competitor-remix.js");

  assert.match(script, /function isActiveRemixStatus/);
  assert.match(script, /state\.detail = \{ remix: \{ status: "queued"/);
  assert.match(script, /const active = isActiveRemixStatus\(remix\.status\)/);
  assert.match(script, /els\.maskConfirmBtn\.disabled = state\.submitBlocked \|\| activeRemix \|\| !state\.source \|\| !state\.regions\.length/);
  assert.match(script, /els\.uploadBtn\.disabled = activeRemix/);
  assert.match(script, /els\.clearMaskBtn\.disabled = activeRemix/);
  assert.match(script, /处理中，请等待状态刷新后再继续操作/);
});
