import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const publicDir = fileURLToPath(new URL("../../public/", import.meta.url));

async function readPublic(name) {
  return readFile(join(publicDir, name), "utf8");
}

test("legacy navigation exposes wangzhuan and competitor remix entries", async () => {
  const index = await readPublic("index.html");
  const comic = await readPublic("comic.html");
  for (const html of [index, comic]) {
    assert.match(html, /href="\/wangzhuan\.html"/);
    assert.match(html, /href="\/competitor-remix\.html"/);
    assert.match(html, /网赚素材管线/);
    assert.match(html, /竞品素材改造/);
  }
});

test("wangzhuan page wires required API flows and states", async () => {
  const html = await readPublic("wangzhuan.html");
  const script = await readPublic("wangzhuan.js");
  const styles = await readPublic("styles.css");
  const common = await readPublic("wangzhuan-common.js");

  assert.match(html, /class="[^"]*\bwz-workbench\b/);
  assert.match(html, /class="[^"]*\bwz-canvas-toolbar\b/);
  assert.match(html, /class="[^"]*\bwz-canvas\b/);
  assert.match(html, /class="[^"]*\bwz-canvas-links\b/);
  assert.match(html, /class="[^"]*\bwz-node\b/);
  assert.match(html, /class="[^"]*\bwz-stepbar-item\b/);
  assert.match(html, /class="[^"]*\bwz-branches\b/);
  assert.match(html, /class="[^"]*\bwz-col-branches\b/);
  assert.match(html, /class="[^"]*\bwz-subflow\b/);
  assert.match(html, /class="[^"]*\bwz-primary-form\b/);
  assert.match(html, /autocomplete="off"/);
  assert.match(html, /class="[^"]*\bwz-advanced-settings\b/);
  assert.match(html, /id="wzStepbar"/);
  assert.match(html, /id="wzCanvas"/);
  assert.match(html, /id="wzCanvasLinks"/);
  assert.match(html, /id="wzBranches"/);
  assert.match(html, /data-node="upload"/);
  assert.match(html, /data-node="decompose"/);
  assert.match(html, /data-node="rewrite"/);
  assert.match(html, /data-node="batch"/);
  assert.match(html, /data-node="log"/);
  assert.match(html, /data-node="output"/);
  assert.match(html, /参考视频输入/);
  assert.match(html, /上传参考/);
  assert.match(html, /模型拆解/);
  assert.match(html, /产品改写/);
  assert.match(html, /可裂变 3\.1 \/ 3\.2 \/ 3\.3/);
  assert.match(html, /裂变子节点/);
  assert.match(html, /改写 3\.1/);
  assert.match(html, /模板与产品信息/);
  assert.match(html, /本次投放/);
  assert.doesNotMatch(html, /<span class="wz-subno">3\.1\.1<\/span>[^<]*模板与批次默认值/);
  assert.match(html, /<span class="wz-subno">3\.1\.1<\/span>[^<]*模板与产品信息/);
  assert.match(html, /<span class="wz-subno">3\.1\.2<\/span>[^<]*我方产品素材资产/);
  assert.match(html, /<span class="wz-subno">3\.1\.3<\/span>[^<]*本次投放/);
  assert.match(html, /提示词规则（可选补充）/);
  assert.match(html, /AI 拆解脚本/);
  assert.match(html, /分析参考视频，提取镜头与脚本结构/);
  assert.match(html, /id="wzLlmServiceStatus"/);
  assert.match(html, /素材经验补充（可选）/);
  assert.match(html, /开始解析/);
  assert.match(html, /id="wzDecompositionForm"/);
  assert.match(html, /产品改写（可裂变/);
  assert.match(html, /批次参数/);
  assert.match(html, /生成批次/);
  assert.match(html, /结果与下载/);
  assert.match(html, /第 4 步子流程/);
  assert.match(html, /生成 Seedance 预案/);
  assert.match(html, /Seedance 2\.0/);
  assert.match(html, /id="wzLlmProvider"/);
  assert.match(html, /id="wzLlmModel"/);
  assert.match(html, /id="wzLlmEndpoint"/);
  assert.match(html, /https:\/\/skylink-gateway\.com\/api\/v1/);
  assert.match(html, /id="wzKnowledgeNotes"/);
  assert.match(html, /id="wzVariantPrompt"/);
  assert.match(html, /id="wzSeedanceModel"/);
  assert.match(html, /id="wzTemplateSelect"/);
  assert.match(html, /开发者选项（一般无需修改）/);
  assert.doesNotMatch(html, /LLM endpoint/);
  assert.match(html, /参考视频/);
  assert.match(html, /运行日志/);
  assert.doesNotMatch(html, /ffprobe/);
  assert.doesNotMatch(html, /GPT JSON 拆解/);
  assert.doesNotMatch(html, /Seedance Prompt/);
  assert.doesNotMatch(html, /id="wzReferenceDuration"/);
  assert.doesNotMatch(html, /id="wzReferenceWidth"/);
  assert.doesNotMatch(html, /id="wzReferenceHeight"/);
  assert.match(html, /id="wzProductLink"/);
  assert.match(html, /id="wzInspectStoreBtn"/);
  assert.match(html, /读取商店页/);
  assert.match(html, /id="wzStoreCandidates"/);
  assert.match(html, /尚未读取商店页资产/);
  assert.match(html, /id="wzProductIconFile"/);
  assert.match(html, /id="wzProductScreenshotFile"/);
  assert.match(html, /id="wzProductRecordingFile"/);
  assert.match(html, /id="wzCtaAssetFile"/);
  assert.match(html, /id="wzEndingAssetFile"/);
  assert.doesNotMatch(html, /id="wzEndingAssetInlineFile"/);
  assert.match(html, /id="wzPersonAssetFile"/);
  assert.match(html, /id="wzRewardElementFile"/);
  assert.match(html, /id="wzMaterialDirection"/);
  assert.match(html, /id="wzVoiceoverStyle"/);
  assert.match(html, /id="wzLanguages"/);
  assert.match(html, /id="wzTargetRegions"/);
  assert.match(html, /id="wzDisclaimerPreset"/);
  assert.match(html, /id="wzDisclaimer"/);
  assert.match(html, /id="wzDisclaimerOverlayPosition"/);
  assert.match(html, /id="wzDisclaimerOverlayFontSize"/);
  assert.match(html, /id="wzDisclaimerOverlayBoxHeight"/);
  assert.match(html, /id="wzDisclaimerOverlayOpacity"/);
  assert.match(html, /id="wzOutputRatio"/);
  assert.match(html, /免责声明/);
  assert.match(html, /<option value="other" selected>其他<\/option>/);
  assert.match(html, /id="wzMaterialDirectionCustom"[^>]*value="跟随竞品"/);
  assert.match(html, /id="wzVoiceoverStyle" type="text" value="遵循竞品"/);
  assert.match(html, /id="wzCta" type="text" value=""/);
  assert.match(html, /id="wzEnding" type="text" value=""/);
  assert.match(html, /Rewards are subject to in-app rules, eligibility, task completion, and regional availability\. Results are not guaranteed\./);
  assert.match(script, /As recompensas dependem das regras do app, elegibilidade, conclusão das tarefas e disponibilidade regional\. Os resultados não são garantidos/);
  assert.match(script, /奖励结果受 App 内活动规则、用户资格、任务完成情况、地区限制和活动时间影响，不保证每位用户都能获得相同奖励。/);
  assert.match(html, /尺寸/);
  assert.match(html, /id="wzCustomPrompt"/);
  assert.match(html, /id="wzNegativePrompt"/);
  assert.match(html, /id="wzReferenceFile"/);
  assert.match(html, />上传视频</);
  assert.match(html, /id="wzConfirmReferenceBtn"/);
  assert.match(html, /确认进入脚本拆解/);
  assert.match(html, /id="wzEstimateBtn"/);
  assert.match(html, /id="wzDownloadBtn"/);
  assert.match(html, /id="wzActiveLockActions"/);
  assert.match(html, /id="wzGlobalError"/);
  assert.doesNotMatch(html, /id="wzStopActiveLockBtn"/);
  assert.doesNotMatch(html, /id="wzTaskSpaceBtn"/);
  assert.match(html, /topbar-account-link.*任务管理/);
  assert.doesNotMatch(html, /platform-nav-item[^>]*href="\/wangzhuan-tasks\.html"/);
  const uploadNode = html.slice(
    html.indexOf('id="wzNodeUpload"'),
    html.indexOf("<!-- 列2：拆解 -->")
  );
  assert.match(uploadNode, /参考视频输入/);
  assert.match(uploadNode, /id="wzProjectName"/);
  assert.match(uploadNode, /id="wzBatchName"/);
  assert.match(uploadNode, /id="wzConfirmReferenceBtn"/);
  assert.doesNotMatch(uploadNode, /id="wzTemplateSelect"/);
  assert.doesNotMatch(uploadNode, /id="wzDisplayName"/);
  assert.doesNotMatch(uploadNode, /id="wzTemplateChannel"/);
  assert.doesNotMatch(uploadNode, /id="wzDefaultDuration"/);
  assert.doesNotMatch(uploadNode, /id="wzEnding"/);
  assert.doesNotMatch(uploadNode, /id="wzCurrencySymbol"/);
  assert.doesNotMatch(uploadNode, /id="wzProductName"/);
  assert.doesNotMatch(uploadNode, /id="wzProductIconFile"/);
  const rewriteNode = html.match(/<section class="[^"]*\bwz-node\b[^"]*" id="wzNodeRewrite"[\s\S]*?<section class="wz-subnode" data-sub="2"/)?.[0] || "";
  assert.match(rewriteNode, /<span class="wz-subno">3\.1\.1<\/span>[^<]*模板与产品信息/);
  assert.match(rewriteNode, /id="wzTemplateSelect"/);
  assert.match(rewriteNode, /id="wzDisplayName"/);
  assert.match(rewriteNode, /模板复用（可选）/);
  assert.match(html, /<option value="other" selected>其他<\/option>/);
  assert.match(html, /id="wzMaterialDirectionCustom"/);
  assert.match(html, /CTA 素材/);
  assert.match(html, /Ending 素材/);
  assert.match(html, /免责声明只作为最终视频后处理贴片/);
  assert.match(html, /这里填写的内容会直接带入 Seedance 预案提示词/);
  assert.match(script, /function defaultUserBatchName/);
  assert.match(script, /wangzhuan_batch_/);
  assert.match(script, /function selectedMaterialDirection/);
  assert.match(script, /function syncMaterialDirectionCustom/);
  assert.match(script, /estimateRequestSignature/);
  assert.match(script, /当前批次 \$\{batchDisplayName\(batch\)\} 进行中/);
  assert.match(script, /\["同时生成数", estimate\.requestedConcurrency\]/);
  assert.match(script, /productLink/);
  assert.match(script, /function renderStoreCandidates/);
  assert.match(script, /function applyStoreCandidate/);
  assert.match(script, /function inspectStorePage/);
  assert.match(script, /\/api\/wangzhuan\/store-page\/inspect/);
  assert.match(script, /data-store-apply="productName"/);
  assert.match(script, /data-store-apply="description"/);
  assert.match(script, /data-store-apply="icon"/);
  assert.match(script, /data-store-apply="screenshots"/);
  assert.match(script, /assetFileNames/);
  assert.match(script, /llmConfig/);
  assert.match(script, /llmEndpoint/);
  assert.match(script, /function resetTransientFormState/);
  assert.match(script, /function startNewTask/);
  assert.match(script, /function restoreUserBatchName/);
  assert.match(script, /function restoreBatchDraftForm/);
  assert.doesNotMatch(html, /value="Perkplay"/);
  assert.match(script, /generateBatchName: true/);
  assert.match(script, /function bootstrapWorkbenchUi/);
  assert.match(script, /bootstrapWorkbenchUi\(\);[\s\S]*renderTruthFields\(\);/);
  assert.match(html, /id="wzStartNewTaskBtn"/);
  assert.match(html, /wz-stepbar-trailing[\s\S]*id="wzStartNewTaskBtn"/);
  assert.match(html, /开始新任务/);
  assert.match(script, /loadLlmConfig/);
  assert.match(script, /renderLlmServiceStatus/);
  assert.match(script, /AI 拆解服务已就绪/);
  assert.match(script, /\/api\/wangzhuan\/llm-config/);
  assert.match(script, /gpt-5\.4/);
  assert.match(script, /解析未完成：/);
  assert.match(script, /knowledgeNotes/);
  assert.match(script, /variantPrompt/);
  assert.match(script, /seedanceModel/);
  assert.match(script, /function splitMultiValue/);
  assert.match(script, /targetRegions/);
  assert.match(script, /languages/);
  assert.match(script, /function disclaimerRequestFields/);
  assert.match(script, /\.\.\.disclaimerFields/);
  assert.match(script, /disclaimerPresetId/);
  assert.match(script, /disclaimerPreset/);
  assert.match(script, /disclaimerLanguage/);
  assert.match(script, /disclaimerByLanguage/);
  assert.match(script, /disclaimerOverlay:/);
  assert.match(script, /outputRatio:\s*els\.outputRatio\?\.value/);
  assert.doesNotMatch(script, /请先保存产品模板，上传参考视频并确认脚本拆解/);
  assert.doesNotMatch(script, /需先完成脚本确认与模板保存/);
  assert.match(script, /materialDirection/);
  assert.match(script, /customPrompt/);
  assert.match(script, /negativePrompt/);
  assert.match(script, /wz-rule-row/);
  assert.match(script, /不是账号权限/);
  assert.match(styles, /\.wz-rule-row/);
  assert.match(styles, /\.wz-rule-groups/);
  assert.match(styles, /\.wz-canvas-toolbar/);
  assert.match(styles, /\.wz-canvas/);
  assert.match(styles, /\.wz-canvas-links/);
  assert.match(styles, /\.wz-node/);
  assert.match(styles, /\.wz-stepbar/);
  assert.match(styles, /\.wz-branches/);
  assert.match(styles, /\.wz-col-branches/);
  assert.match(styles, /\.wz-primary-form/);
  assert.match(styles, /\.wz-advanced-settings/);
  assert.match(script, /\/api\/wangzhuan\/templates/);
  assert.match(script, /copyFromVersionId:\s*state\.selectedTemplate\.versionId/);
  assert.match(script, /selectedTemplateNameChanged/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/check/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/draft-decomposition/);
  assert.match(script, /draftReferenceVideoDecomposition/);
  assert.match(script, /file_required/);
  assert.match(script, /请选择一个真实参考视频文件，系统会读取时长、画幅和音轨信息/);
  assert.match(script, /读取视频信息/);
  assert.match(script, /估算本批任务/);
  assert.match(script, /ESTIMATE_BTN_LABEL/);
  assert.match(script, /syncEstimateButtonLabel/);
  assert.match(html, /id="wzEstimateBtn"/);
  assert.doesNotMatch(html, /id="wzEstimateBtn"[^>]*>重新估算</);
  assert.doesNotMatch(script, /tinyVideoDataUrl\("reference"\)/);
  assert.doesNotMatch(script, /sample-reference\.mp4/);
  assert.match(script, /画幅/);
  assert.match(script, /码率/);
  assert.match(script, /音轨/);
  assert.doesNotMatch(script, /durationSec: Number\(els\.referenceDuration\.value\)/);
  assert.doesNotMatch(script, /width: Number\(els\.referenceWidth\.value\)/);
  assert.doesNotMatch(script, /height: Number\(els\.referenceHeight\.value\)/);
  assert.doesNotMatch(script, /canExtractFrame: true/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/decompose/);
  assert.match(script, /\/api\/wangzhuan\/reference-videos\/\$\{encodeURIComponent\(referenceVideoId\)\}\/workflow-state/);
  assert.match(script, /restoreWorkflowSession/);
  assert.match(script, /isBlockingPipelineBatch/);
  assert.match(script, /renderBatchReadiness/);
  assert.match(script, /WORKFLOW_SESSION_KEY/);
  assert.match(script, /再次保存将写入新版本/);
  assert.match(html, /id="wzBatchReadiness"/);
  assert.match(html, /id="wzConfirmRewriteBtn"/);
  assert.match(html, /id="wzRewriteStatus"/);
  assert.match(html, /保存模板是可选项/);
  assert.match(html, /wz-save-template-btn/);
  assert.match(script, /saveTemplateButtons/);
  assert.match(script, /templateSaveStatusNodes/);
  assert.match(script, /confirmRewriteInfo/);
  assert.match(script, /rewriteConfirmed/);
  assert.match(script, /isRewriteConfirmed/);
  assert.match(styles, /\.wz-batch-readiness/);
  assert.match(script, /wzFocusNodeId/);
  assert.match(script, /window\.wzFocusNode/);
  assert.match(styles, /\.wz-focus-mode/);
  assert.match(script, /\/api\/wangzhuan\/batches\/estimate/);
  assert.match(script, /\/api\/wangzhuan\/batches\/plan/);
  assert.match(script, /confirmBatchPlanRequest/);
  assert.doesNotMatch(script, /\/api\/wangzhuan\/batches\/start/);
  assert.match(html, /id="wzPlanBatchBtn"/);
  assert.match(html, /id="wzConfirmPlanBtn"/);
  assert.match(html, /id="wzPlanBox"/);
  assert.match(html, /生成 Seedance 预案/);
  assert.match(html, /wz-batch-steps/);
  assert.match(html, /估算结果/);
  assert.doesNotMatch(html, /生成第4步预案/);
  assert.match(html, /确认预案并生成视频/);
  assert.doesNotMatch(html, /id="wzStartBatchBtn"/);
  assert.match(script, /wangzhuan-task-nav\.js/);
  assert.match(script, /showActiveLockFromError/);
  assert.match(common, /taskSpaceHref/);
  assert.match(common, /wangzhuan-tasks\.html/);
  assert.match(common, /打开任务管理/);
  assert.match(common, /confirmBatchPlanRequest/);
  assert.match(script, /confirmBatchPlanRequest/);
  assert.match(script, /collectEditablePlans/);
  assert.match(script, /data-plan-field="seedancePrompt"/);
  assert.match(script, /wz-plan-editor/);
  assert.match(script, /renderOutputPreview/);
  assert.match(script, /<video src="\$\{safeUrl\}" controls preload="metadata" playsinline><\/video>/);
  assert.match(common, /plans:\s*plans\.map/);
  assert.match(script, /galleryPageSize:\s*20/);
  assert.match(script, /pageSize:\s*String\(state\.galleryPageSize\)/);
  assert.match(script, /sourceType:\s*"pipeline"/);
  assert.doesNotMatch(script, /query\.set\("batchId"/);
  assert.match(script, /data-gallery-page/);
  assert.match(styles, /\.wz-gallery-pager/);
  assert.match(styles, /\.wz-lock-actions/);
  assert.match(common, /payload\.code !== "ok"/);
  assert.match(common, /requestId/);
});

test("competitor remix page exposes task-oriented video-ops flow", async () => {
  const html = await readPublic("competitor-remix.html");
  const script = await readPublic("competitor-remix.js");
  const styles = await readPublic("styles.css");

  assert.match(html, /class="[^"]*\bwz-workbench\b/);
  assert.match(html, /autocomplete="off"/);
  assert.match(html, /id="remixStepbar"/);
  assert.match(html, /id="remixCanvas"/);
  assert.match(html, /id="remixCanvasLinks"/);
  assert.match(html, /data-node="task"/);
  assert.match(html, /data-node="input"/);
  assert.match(html, /data-node="job"/);
  assert.match(html, /选择任务/);
  assert.match(html, /输入与参数/);
  assert.match(html, /队列与结果/);
  assert.match(html, /真实可接入任务/);
  assert.match(html, /id="videoOpsTaskGrid"/);
  assert.match(html, /id="videoOpsSourceUrl"/);
  assert.match(html, /id="videoOpsSourceFile"/);
  assert.match(html, /单个视频不超过 300 MB/);
  assert.match(html, /id="videoOpsReportText"/);
  assert.match(html, /id="videoOpsPayloadPreview"/);
  assert.match(html, /id="videoOpsSubmitBtn"/);
  assert.match(html, /id="videoOpsRefreshBtn"/);
  assert.match(html, /id="videoOpsResultBtn"/);
  assert.match(html, /id="videoOpsDownloadBtn"/);
  assert.match(html, /id="videoOpsCancelBtn"/);
  assert.match(html, /id="videoOpsRetryBtn"/);
  assert.match(html, /id="videoOpsFrameCanvas"/);
  assert.match(html, /id="videoOpsPromptLayer"/);
  assert.match(html, /id="interactivePromptType"/);
  assert.match(html, /Point Prompt/);
  assert.match(html, /Box Prompt/);
  assert.match(html, /id="manualMaskFile"/);
  assert.match(html, /id="videoOpsRegionOverlay"/);
  assert.doesNotMatch(html, /产品名替换/);
  assert.doesNotMatch(html, /CTA 文案替换/);
  assert.doesNotMatch(html, /自动识别建议/);
  assert.doesNotMatch(html, /Mask 区域预览/);
  assert.doesNotMatch(html, /id="remixMaskConfirmBtn"/);
  assert.doesNotMatch(html, /id="remixCapabilitySelect"/);
  assert.doesNotMatch(html, /id="remixPrototypeTaskQueue"/);
  assert.doesNotMatch(html, /识别候选区域/);
  assert.doesNotMatch(html, /执行计划预览/);
  assert.match(script, /seedance_ai_remove/);
  assert.match(script, /一键去标识/);
  assert.match(script, /auto_ai_remove/);
  assert.match(script, /ai_remove_manual/);
  assert.match(script, /mask_edit/);
  assert.match(script, /sticker_blur/);
  assert.match(script, /end_trim_detection/);
  assert.match(script, /尾段检测/);
  assert.match(script, /video_copy_translate/);
  assert.match(script, /字幕翻译回写/);
  assert.match(script, /language_rewrite/);
  assert.match(script, /语言改写/);
  assert.match(script, /material_analysis/);
  assert.match(script, /素材分析/);
  assert.match(script, /interaction_prompt/);
  assert.match(script, /prompt_type: "point"/);
  assert.match(script, /prompt_type: "box"/);
  assert.match(script, /mode: "manual"/);
  assert.match(script, /mask_source/);
  assert.match(script, /time_ranges/);
  assert.match(script, /region_spec/);
  assert.match(script, /source_type: "base64_data_url"/);
  assert.match(script, /source_type: "report_text"/);
  assert.match(script, /\/api\/wangzhuan\/video-ops\/jobs/);
  assert.match(script, /include_model_calls=true/);
  assert.match(script, /schedulePoll/);
  assert.match(script, /TERMINAL_STATUSES/);
  assert.doesNotMatch(script, /\/api\/wangzhuan\/remix\/detect/);
  assert.doesNotMatch(script, /\/api\/wangzhuan\/remix\/plan/);
  assert.doesNotMatch(script, /DEFAULT_AUTO_CAPABILITY_KEYS/);
  assert.doesNotMatch(script, /function renderDetection/);
  assert.doesNotMatch(script, /function renderPlan/);
  assert.doesNotMatch(script, /remixPrototype/);
  assert.doesNotMatch(script, /产品名替换/);
  assert.doesNotMatch(script, /CTA 文案替换/);
  assert.match(styles, /.video-ops-task-grid/);
  assert.match(styles, /.video-ops-kframe-layout/);
  assert.match(styles, /.video-ops-prompt-layer/);
  assert.match(styles, /.video-ops-region-overlay/);
  assert.match(styles, /.video-ops-result-box/);
});

test("competitor remix canvas wires video-ops node topology", async () => {
  const canvas = await readPublic("remix-canvas.js");
  const html = await readPublic("competitor-remix.html");

  assert.match(html, /id="remixNodeTask"/);
  assert.match(html, /id="remixNodeInput"/);
  assert.match(html, /id="remixNodeJob"/);
  assert.match(html, /id="remixNodeResult"/);
  assert.match(canvas, /id\("remixNodeTask"\)/);
  assert.match(canvas, /id\("remixNodeInput"\)/);
  assert.match(canvas, /id\("remixNodeJob"\)/);
  assert.match(canvas, /id\("remixNodeResult"\)/);
  assert.doesNotMatch(canvas, /remixNodeSource/);
  assert.doesNotMatch(canvas, /remixNodeMask/);
});
test("task management page exposes dedicated task space", async () => {
  const html = await readPublic("wangzhuan-tasks.html");
  const script = await readPublic("wangzhuan-tasks.js");
  const styles = await readPublic("styles.css");

  assert.match(html, /任务管理/);
  assert.match(html, /topbar-account-link active.*wangzhuan-tasks\.html/);
  assert.doesNotMatch(html, /platform-nav-item[^>]*href="\/wangzhuan-tasks\.html"/);
  assert.match(html, /id="wzTasksList"/);
  assert.match(html, /id="wzTasksDetail"/);
  assert.match(html, /wzTasksTypePipeline/);
  assert.match(html, /网赚素材管线/);
  assert.match(html, /竞品素材改造/);
  assert.match(script, /\/api\/wangzhuan\/tasks/);
  assert.match(script, /renderTaskMediaCompare/);
  assert.match(script, /pickPrimaryOutput/);
  assert.match(script, /runType/);
  assert.match(script, /confirmBatchPlan/);
  assert.match(script, /wzTasksRunQcBtn/);
  assert.match(script, /运行视频质检/);
  assert.match(script, /\/api\/wangzhuan\/batches\/\$\{encodeURIComponent\(batch\.batchId\)\}\/qc/);
  assert.match(script, /batch\.status === "qc" \? "放弃批次" : "停止任务"/);
  assert.match(script, /workbenchHref/);
  assert.match(styles, /\.wz-tasks-layout/);
  assert.match(styles, /\.wz-tasks-media-stage/);
  assert.match(styles, /\.wz-tasks-type-badge/);
});

test("wangzhuan confirmation keeps saved decomposition state clear", async () => {
  const script = await readPublic("wangzhuan.js");
  const html = await readPublic("wangzhuan.html");

  assert.match(script, /function isDecompositionConfirmed/);
  assert.match(script, /脚本拆解已确认，请继续填写第三步产品改写/);
  assert.match(script, /TEMPLATE_SAVED_MESSAGE/);
  assert.match(script, /isTemplateCommitted/);
  assert.match(script, /setTemplateCommitted/);
  assert.match(script, /setRewriteConfirmed/);
  assert.match(html, /id="wzRewriteStatus"/);
  assert.match(script, /function syncDecompositionControls/);
  assert.match(script, /flattenDecompositionFieldValue/);
  assert.match(script, /fitDecompositionTextareas/);
  assert.match(script, /wz-decomposition-input/);
  assert.match(script, /开始解析/);
  assert.match(script, /重新解析/);
  assert.doesNotMatch(script, /wzDecompositionText/);
  assert.doesNotMatch(script, /els\.decomposeBtn\.disabled = isDecompositionConfirmed\(\) \|\| !els\.decompositionText\.value\.trim\(\)/);
});

test("wangzhuan locks upstream workflow after seedance plan confirm", async () => {
  const script = await readPublic("wangzhuan.js");
  const styles = await readPublic("styles.css");

  assert.match(script, /function isSeedancePlanConfirmed/);
  assert.match(script, /function isUpstreamWorkflowLocked/);
  assert.match(script, /function syncUpstreamWorkflowLock/);
  assert.match(script, /previewConfirmedAt/);
  assert.match(script, /dataset\.workflowFrozen/);
  assert.match(script, /Seedance 已提交生成，前序步骤已锁定/);
  assert.match(script, /批次已停止/);
  assert.match(script, /clearActiveLockBanner\(lockHost\(\)\)/);
  assert.match(script, /showToast\("批次已停止"/);
  assert.match(styles, /#wzCanvas\[data-workflow-frozen\]/);
});

test("wangzhuan branch nodes are collected and persisted as editable drafts", async () => {
  const script = await readPublic("wangzhuan.js");
  const canvas = await readPublic("wz-canvas.js");

  assert.match(script, /function collectBranchDrafts/);
  assert.match(script, /function applyBranches/);
  assert.match(script, /branches: collectBranchDrafts\(\)/);
  assert.match(script, /branchId/);
  assert.match(script, /branchLabel/);
  assert.match(script, /assetUrls/);
  assert.match(script, /assetStorageKeys/);
  assert.match(script, /await uploadBranchAssets\(\)/);
  assert.match(script, /templateSnapshot/);
  assert.match(script, /branchCount/);
  assert.match(canvas, /window\.wzCreateBranchNode/);
  assert.match(canvas, /wz-branch-remove/);
  assert.match(canvas, /wz-save-template-btn/);
  assert.doesNotMatch(canvas, /wz-template-save-block\)\?\.remove/);
  assert.doesNotMatch(canvas, /后端多分支接口就绪后/);
  assert.doesNotMatch(canvas, /Strip identity from the clone so it can't break ID-based business JS/);
});

test("wangzhuan generation progress exposes upstream task visibility", async () => {
  const common = await readPublic("wangzhuan-common.js");
  const script = await readPublic("wangzhuan.js");
  const styles = await readPublic("styles.css");

  assert.match(common, /export function isBatchGenerationActive/);
  assert.match(common, /export function renderGenerationTaskCards/);
  assert.match(common, /export function formatWorkflowEvent/);
  assert.match(script, /renderGenerationTaskCards\(tasks\)/);
  assert.match(script, /formatWorkflowEvent\(event\)/);
  assert.match(script, /isBatchGenerationActive\(batch, tasks\)/);
  assert.match(styles, /\.wz-generation-panel/);
});

test("wangzhuan batch qc state distinguishes generation done from qc running", async () => {
  const common = await readPublic("wangzhuan-common.js");
  const script = await readPublic("wangzhuan.js");

  assert.match(common, /export function batchStatusDisplayLabel/);
  assert.match(common, /export function batchGenerationProgress/);
  assert.match(common, /export function isBatchQcRunnable/);
  assert.match(common, /downloaded: "已下载"/);
  assert.match(common, /qc: "待质检"/);
  assert.match(script, /isBatchQcRunnable\(batch, tasks, outputs\)/);
  assert.match(script, /function isQcBatchPending/);
  assert.match(script, /当前批次已生成完成，请先运行视频质检或放弃批次/);
  assert.match(script, /els\.estimateBtn\) els\.estimateBtn\.disabled = isQcBatchPending\(batch\)/);
  assert.match(script, /isQcBatchPending\(batch\) \? "放弃批次" : "停止任务"/);
  assert.match(script, /omni_reference/);
});

test("wangzhuan keeps step 4 focused until seedance plan is confirmed", async () => {
  const script = await readPublic("wangzhuan.js");
  const canvas = await readPublic("wz-canvas.js");

  assert.match(script, /function normalizeAssetReviewStatus/);
  assert.match(script, /function isAssetReviewFailureStatus/);
  assert.match(script, /function applyAssetReviewFailureFromError/);
  assert.match(script, /async function uploadSeedanceAssetsForReview/);
  assert.match(script, /syncBatchNodeStatus/);
  assert.match(script, /dataset\.batchStatus/);
  assert.match(script, /focusBatchStep\(\);\s*\n\s*showToast\("Seedance 预案已生成/);
  assert.match(script, /focusLogStep\(\);\s*\n\s*showToast\("批次已提交 Seedance 生成/);
  assert.match(canvas, /status === "preview_required"\) return false/);
  assert.match(canvas, /data-batch-status/);
});

test("competitor remix video-ops page gates submit and active job controls", async () => {
  const script = await readPublic("competitor-remix.js");

  assert.match(script, /const RUNNING_STATUSES = new Set/);
  assert.match(script, /const TERMINAL_STATUSES = new Set/);
  assert.match(script, /function renderSubmitState/);
  assert.match(script, /function jobFailureMessage/);
  assert.match(script, /failure_reason/);
  assert.match(script, /RUNNING_STATUSES\.has\(state\.job\.status\)/);
  assert.match(script, /MAX_UPLOAD_VIDEO_BYTES/);
  assert.match(script, /function validateSubmitReady/);
  assert.match(script, /els\.submitBtn\.disabled = !state\.user \|\| state\.submitting \|\| running \|\| !ready\.ok/);
  assert.match(script, /els\.submitBtn\.title = ready\.ok \? "" : ready\.message/);
  assert.match(script, /els\.cancelBtn\.disabled = !id \|\| terminal/);
  assert.match(script, /els\.retryBtn\.disabled = !id \|\| job\?\.status !== "failed"/);
  assert.match(script, /els\.downloadBtn\.disabled = !id \|\| !\(job\?\.status === "succeeded" \|\| job\?\.status === "review_required"\)/);
  assert.match(script, /setBusy\(els\.submitBtn, true, "提交中"\)/);
  assert.match(script, /showLogin\(els\.loginModal\)/);
  assert.match(script, /bindLogin/);
  assert.doesNotMatch(script, /function isActiveRemixStatus/);
  assert.doesNotMatch(script, /state.initFailed/);
});
test("release packaging excludes exported environment dumps", async () => {
  const gitignore = await readFile(join(publicDir, "../.gitignore"), "utf8");
  const dockerignore = await readFile(join(publicDir, "../.dockerignore"), "utf8");
  const releaseScript = await readFile(join(publicDir, "../package-release.ps1"), "utf8");

  assert.match(gitignore, /^env\.export\.txt$/m);
  assert.match(dockerignore, /^env\.export\.txt$/m);
  assert.match(releaseScript, /env\.export\.txt/);
});
