import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../../", import.meta.url);

async function readText(path) {
  return readFile(new URL(path, root), "utf8");
}

test("wangzhuan v2 page keeps old page separate and exposes dense workbench regions", async () => {
  const html = await readText("public/wangzhuan-v2.html");
  assert.match(html, /<title>[^<]*网赚素材管线 v2/);
  assert.match(html, /href="\/wangzhuan\.html"[\s\S]*网赚素材管线/);
  assert.match(html, /href="\/wangzhuan-v2\.html"[\s\S]*网赚素材管线 v2/);
  assert.match(html, /id="wzV2TaskQueue"/);
  assert.match(html, /id="wzSaveDraftBtn"/);
  assert.match(html, /id="wzGlobalError"/);
  assert.match(html, /id="wzLoginModal"/);
  assert.match(html, /后台任务队列/);
  assert.match(html, /关键提醒/);
  assert.match(html, /查看日志/);
  assert.match(html, /运行与结果/);
});

test("wangzhuan v2 page uses required native controls and field labels", async () => {
  const html = await readText("public/wangzhuan-v2.html");
  assert.match(html, /id="wzReferencePreview"/);
  assert.match(html, /id="wzUploadSeedanceAssetsBtn"/);
  assert.match(html, /上传 Seedance 素材并审核/);
  assert.match(html, /id="wzConfirmAssetsBtn"/);
  assert.match(html, /id="wzAddBranchBtn"/);
  assert.match(html, /id="wzBranchTabs"/);
  assert.match(html, /\+ 裂变子节点/);
  assert.match(html, /<select id="wzTargetRegion">/);
  assert.doesNotMatch(html, /id="wzTargetRegions"[^>]*multiple/);
  assert.match(html, /<select id="wzLanguage">/);
  assert.doesNotMatch(html, /id="wzLanguages"[^>]*multiple/);
  assert.match(html, /<select id="wzCurrencySymbol">/);
  assert.match(html, /<option value="R\$">R\$ BRL<\/option>/);
  assert.match(html, /<option value="MX\$">MX\$ MXN<\/option>/);
  assert.match(html, /<option value="custom">自定义<\/option>/);
  assert.match(html, /id="wzCurrencyCustom"/);
  assert.match(html, /id="wzTruthDetails"/);
  assert.match(html, /强承诺真实规则/);
  assert.match(html, /id="wzTruthFields"/);
  assert.match(html, /id="wzInspectStoreBtn"[^>]*disabled/);
  assert.match(html, /免责声明贴片模板/);
  assert.match(html, /id="wzDisclaimerOverlayPosition"/);
  assert.match(html, /id="wzDisclaimerOverlayFontSize"/);
  assert.match(html, /id="wzDisclaimerOverlayBoxHeight"/);
  assert.match(html, /id="wzDisclaimerOverlayBottomMargin"/);
  assert.match(html, /id="wzDisclaimerOverlayHorizontalMargin"/);
  assert.match(html, /脚本裂变规则补充/);
  assert.match(html, /变体数 \* 同时生成数量 \* 3min/);
  assert.match(html, /id="wzPlanLlmModel"/);
  assert.match(html, /id="wzConfirmLimits"/);
  assert.match(html, /<option value="gemini-3\.5-flash" selected>Gemini 3\.5 Flash<\/option>/);
  assert.match(html, /<option value="gemini-3\.1-pro-preview">Gemini 3\.1 Pro Preview<\/option>/);
  assert.doesNotMatch(html, /id="wzDecomposeBtn"/);
  assert.doesNotMatch(html, /确认脚本拆解/);
  assert.doesNotMatch(html, /id="wzConfirmReferenceBtn"/);
  assert.doesNotMatch(html, /确认进入脚本拆解/);
});

test("wangzhuan v2 script submits array-compatible selects and uses background jobs", async () => {
  const js = await readText("public/wangzhuan-v2.js");
  assert.match(js, /targetRegions:\s*\[region\]/);
  assert.match(js, /languages:\s*\[language\]/);
  assert.match(js, /\/api\/wangzhuan\/reference-videos\/decomposition-jobs/);
  assert.match(js, /\/api\/wangzhuan\/batches\/plan-jobs/);
  assert.match(js, /draftSignatureInput/);
  assert.match(js, /stalePlanPreview/);
  assert.match(js, /wzPlanStaleNotice/);
  assert.match(js, /ensureBatchName\(\)/);
  assert.match(js, /function collectBranchDrafts\(\)/);
  assert.match(js, /branchDrafts:\s*estimateRequest\(\)\.branches/);
  assert.match(js, /const branches = collectBranchDrafts\(\)/);
  assert.match(js, /\/api\/wangzhuan\/product-assets\/upload/);
  assert.match(js, /\/confirm-assets/);
  assert.match(js, /\/api\/wangzhuan\/batches\/draft/);
  assert.match(js, /function currentBatchId\(\)/);
  assert.match(js, /batchId:\s*currentBatchId\(\)\s*\|\|\s*undefined/);
  assert.match(js, /referenceVideo:\s*state\.referenceVideo/);
  assert.match(js, /branchDrafts:\s*estimateRequest\(\)\.branches/);
  assert.match(js, /\/api\/auth/);
  assert.match(js, /\/api\/login/);
  assert.match(js, /loadTemplates/);
  assert.match(js, /applyTemplate/);
  assert.match(js, /confirmRewriteInfo/);
  assert.match(js, /renderPlanEditors/);
  assert.match(js, /renderReminders/);
  assert.match(js, /disclaimerRequestFields/);
  assert.match(js, /function currentDecomposition\(\)/);
  assert.match(js, /decomposition:\s*currentDecomposition\(\)/);
  assert.doesNotMatch(js, /\/api\/wangzhuan\/reference-videos\/decompose/);
  assert.doesNotMatch(js, /wzv2-decompose-/);
  assert.doesNotMatch(js, /confirmDecomposition/);
  assert.doesNotMatch(js, /confirmReferenceBtn/);
  assert.match(js, /\/confirm-plan/);
  assert.match(js, /wzv2-confirm-/);
  assert.match(js, /confirmedPlanIds/);
  assert.match(js, /draftSignature:\s*state\.draftSignature/);
  assert.match(js, /clientPlanDraftSignature/);
  assert.match(js, /isBatchQcRunnable/);
  assert.match(js, /\/stop/);
  assert.match(js, /\/qc/);
  assert.match(js, /startBatchPolling/);
  assert.match(js, /DECOMPOSITION_LLM_TIMEOUT_MS\s*=\s*180_000/);
  assert.match(js, /DECOMPOSITION_JOB_TIMEOUT_MS\s*=\s*180_000/);
  assert.match(js, /maxRetries:\s*0/);
  assert.match(js, /failBackgroundJob/);
  assert.match(js, /job_poll_timeout/);
  assert.match(js, /decompositionEditedFields:\s*new Set\(\)/);
  assert.match(js, /resetDecompositionDraft\(\{\s*clearForm:\s*true\s*\}\)/);
  assert.match(js, /state\.decompositionEditedFields\.clear\(\)/);
  assert.match(js, /state\.decompositionEditedFields\.has\(field\)/);
  assert.match(js, /dataset\?\.decompositionField/);
  assert.match(js, /decompositionForm\.classList\.remove\("empty-line"\)/);
  assert.match(js, /decompositionForm\.classList\.add\("empty-line"\)/);
  assert.match(js, /已回填到页面/);
  assert.match(js, /strongTruthFields/);
  assert.match(js, /function collectTruthRules\(\)/);
  assert.match(js, /truthRules:\s*collectTruthRules\(\)/);
  assert.match(js, /function currencyValue\(\)/);
  assert.match(js, /currencySymbol:\s*currencyValue\(\)/);
  assert.match(js, /function effectiveMaterialDirection\(\)/);
  assert.match(js, /materialDirection:\s*effectiveMaterialDirection\(\)/);
  assert.doesNotMatch(js, /materialDirection:\s*value\(els\.materialDirection\)/);
  assert.match(js, /templateSnapshot:\s*\{\s*draft:\s*\{/);
  assert.match(js, /targetChannels:\s*\[value\(els\.targetChannel\)\s*\|\|\s*"meta_ads"\]/);
  assert.match(js, /targetRegions:\s*\[region\]/);
  assert.match(js, /regions:\s*\[region\]/);
  assert.match(js, /language,\s*\n\s*languages:\s*\[language\]/);
  assert.match(js, /voiceoverStyle:\s*value\(els\.voiceoverStyle\)/);
  assert.match(js, /cta:\s*value\(els\.cta\)/);
  assert.match(js, /ending:\s*value\(els\.ending\)/);
  assert.match(js, /variantPrompt:\s*value\(els\.variantPrompt\)/);
  assert.match(js, /customPrompt:\s*value\(els\.customPrompt\)/);
  assert.match(js, /negativePrompt:\s*value\(els\.negativePrompt\)/);
  assert.match(js, /批次轮询暂时断开，正在重连/);
  assert.match(js, /批次轮询已恢复/);
});

test("confirming Seedance asset reviews is not blocked by preview stage", async () => {
  const source = await readText("server/wangzhuan/pipeline.mjs");
  const start = source.indexOf("export async function confirmBatchAssets");
  const end = source.indexOf("function cleanConfirmationNotes", start);
  const confirmAssetsBody = start >= 0 && end > start ? source.slice(start, end) : "";

  assert.ok(confirmAssetsBody, "confirmBatchAssets implementation should be present");
  assert.doesNotMatch(confirmAssetsBody, /batch\.status\s*!==\s*"preview_required"/);
  assert.doesNotMatch(confirmAssetsBody, /当前批次不在预案确认阶段/);
  assert.match(confirmAssetsBody, /ensureAssetReviewsApproved/);
  assert.match(confirmAssetsBody, /asset_review_pending/);
});
