import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../../", import.meta.url);

async function readText(path) {
  return readFile(new URL(path, root), "utf8");
}

test("wangzhuan v2 page keeps old page separate and exposes dense workbench regions", async () => {
  const html = await readText("public/wangzhuan-v2.html");
  assert.match(html, /<title>[^<]*网赚素材管线 v2/);
  assert.doesNotMatch(html, /href="\/wangzhuan\.html"/);
  assert.match(html, /href="\/wangzhuan-v2\.html"[\s\S]*网赚素材管线/);
  assert.match(html, /id="wzV2TaskQueue"/);
  assert.match(html, /id="wzSaveDraftBtn"/);
  assert.match(html, /id="wzGlobalError"/);
  assert.match(html, /id="wzLoginModal"/);
  assert.match(html, /后台任务队列/);
  assert.match(html, /关键提醒/);
  assert.match(html, /查看日志/);
  assert.match(html, /运行与结果/);
});

test("wangzhuan v2 page uses required native controls and field labels", async () => {
  const html = await readText("public/wangzhuan-v2.html");
  assert.match(html, /id="wzReferencePreview"/);
  assert.match(html, /id="wzUploadSeedanceAssetsBtn"/);
  assert.match(html, /上传 Seedance 素材并审核/);
  assert.match(html, /id="wzConfirmAssetsBtn"/);
  assert.match(html, /id="wzAddBranchBtn"/);
  assert.match(html, /id="wzBranchTabs"/);
  assert.match(html, /\+ 裂变子节点/);
  assert.match(html, /<select id="wzTargetRegion">/);
  assert.doesNotMatch(html, /id="wzTargetRegions"[^>]*multiple/);
  assert.match(html, /<select id="wzLanguage">/);
  assert.doesNotMatch(html, /id="wzLanguages"[^>]*multiple/);
  assert.match(html, /<select id="wzCurrencySymbol">/);
  assert.match(html, /<option value="R\$">R\$ BRL<\/option>/);
  assert.match(html, /<option value="MX\$">MX\$ MXN<\/option>/);
  assert.match(html, /<option value="custom">自定义<\/option>/);
  assert.match(html, /id="wzCurrencyCustom"/);
  assert.match(html, /id="wzTruthDetails"/);
  assert.match(html, /强承诺真实规则/);
  assert.match(html, /id="wzTruthFields"/);
  assert.match(html, /id="wzInspectStoreBtn"[^>]*disabled/);
  assert.match(html, /免责声明贴片模板/);
  assert.match(html, /id="wzDisclaimerOverlayFile"/);
  assert.match(html, /id="wzDisclaimerOverlayPreview"/);
  assert.match(html, /id="wzDisclaimerOverlayPosition"/);
  assert.match(html, /id="wzDisclaimerOverlayBoxHeight"/);
  assert.match(html, /id="wzDisclaimerOverlayBottomMargin"/);
  assert.match(html, /id="wzDisclaimerOverlayHorizontalMargin"/);
  assert.doesNotMatch(html, /id="wzDisclaimer"/);
  assert.doesNotMatch(html, /免责声明文案/);
  assert.doesNotMatch(html, /id="wzDisclaimerOverlayFontSize"/);
  assert.match(html, /脚本裂变规则补充/);
  assert.match(html, /变体数 \* 同时生成数量 \* 3min/);
  assert.match(html, /id="wzLlmModel"/);
  assert.match(html, /id="wzPlanLlmModel"/);
  assert.match(html, /id="wzConfirmLimits"/);
  assert.match(html, /<option value="gemini-3\.1-pro-preview">Gemini 3\.1 Pro Preview<\/option>/);
  assert.match(html, /id="wzGeminiDecompositionHint"[\s\S]*视频拆解通常需要 1-3 分钟/);
  assert.match(html, /<select id="wzLlmModel">[\s\S]*<option value="gpt-5\.5" selected>GPT-5\.5<\/option>/);
  assert.match(html, /<select id="wzPlanLlmModel">[\s\S]*<option value="gpt-5\.5" selected>GPT-5\.5<\/option>/);
  assert.doesNotMatch(html, /<option value="gemini-3\.5-flash"/);
  assert.doesNotMatch(html, /Gemini 3\.5 Flash/);
  assert.doesNotMatch(html, /id="wzDecomposeBtn"/);
  assert.doesNotMatch(html, /确认脚本拆解/);
  assert.doesNotMatch(html, /id="wzConfirmReferenceBtn"/);
  assert.doesNotMatch(html, /确认进入脚本拆解/);
});

test("wangzhuan v2 script submits array-compatible selects and uses background jobs", async () => {
  const js = await readText("public/wangzhuan-v2.js");
  assert.match(js, /targetRegions:\s*\[region\]/);
  assert.match(js, /languages:\s*\[language\]/);
  assert.match(js, /\/api\/wangzhuan\/reference-videos\/decomposition-jobs/);
  assert.match(js, /\/api\/wangzhuan\/batches\/plan-jobs/);
  assert.match(js, /const GEMINI_DECOMPOSITION_TIMEOUT_MS = 300_000/);
  assert.match(js, /function syncGeminiDecompositionHint\(\)/);
  assert.match(js, /startsWith\("gemini-"\)/);
  assert.match(js, /timeoutMs = decompositionTimeoutMs\(model\)/);
  assert.match(js, /Gemini 视频拆解可能持续数分钟/);
  assert.match(js, /els\.draftDecompositionBtn\.disabled = hasGeneratedSeedancePlan\(\)/);
  assert.match(js, /如需调整，可重新拆解/);
  assert.match(js, /PLAN_UPSTREAM_LOCK_SELECTOR/);
  assert.match(js, /function hasGeneratedSeedancePlan/);
  assert.match(js, /function setPlanUpstreamLocked\(locked\)/);
  assert.match(js, /setPlanUpstreamLocked\(planUpstreamLocked\)/);
  assert.match(js, /const planRetryable = isRecoverableBackgroundJob\(state\.planJob\)/);
  assert.match(js, /els\.planBatchBtn\.disabled = planRetryable/);
  assert.match(js, /els\.confirmPlanBtn\.disabled = state\.confirmPlanSubmitting \|\| !plans\.length/);
  assert.match(js, /state\.confirmPlanSubmitting = true/);
  assert.match(js, /log\("正在确认预案并提交 Seedance\.\.\."\)/);
  assert.match(js, /setBusy\(els\.confirmPlanBtn, true, "提交中"\)/);
  assert.match(js, /finally \{\s*\n\s*state\.confirmPlanSubmitting = false/);
  assert.match(js, /setPlanUpstreamLocked\(true\)/);
  assert.match(js, /if \(type === "plan"\) setPlanUpstreamLocked\(false\)/);
  assert.match(js, /setPlanUpstreamLocked\(false\);\s*\n\s*state\.referenceVideo = null/);
  assert.match(js, /draftSignatureInput/);
  assert.match(js, /stalePlanPreview/);
  assert.match(js, /wzPlanStaleNotice/);
  assert.match(js, /ensureBatchName\(\)/);
  assert.match(js, /function collectBranchDrafts\(\)/);
  assert.match(js, /branchDrafts:\s*estimateRequest\(\)\.branches/);
  assert.match(js, /const branches = collectBranchDrafts\(\)/);
  assert.match(js, /\/api\/wangzhuan\/product-assets\/upload/);
  assert.match(js, /\/confirm-assets/);
  assert.match(js, /\/api\/wangzhuan\/batches\/draft/);
  assert.match(js, /function currentBatchId\(\)/);
  assert.match(js, /batchId:\s*currentBatchId\(\)\s*\|\|\s*undefined/);
  assert.match(js, /referenceVideo:\s*state\.referenceVideo/);
  assert.match(js, /branchDrafts:\s*estimateRequest\(\)\.branches/);
  assert.match(js, /\/api\/auth/);
  assert.match(js, /\/api\/login/);
  assert.match(js, /loadTemplates/);
  assert.match(js, /applyTemplate/);
  assert.match(js, /confirmRewriteInfo/);
  assert.match(js, /renderPlanEditors/);
  assert.match(js, /renderReminders/);
  assert.match(js, /disclaimerRequestFields/);
  assert.match(js, /function currentDecomposition\(\)/);
  assert.match(js, /decomposition:\s*currentDecomposition\(\)/);
  assert.doesNotMatch(js, /\/api\/wangzhuan\/reference-videos\/decompose/);
  assert.doesNotMatch(js, /wzv2-decompose-/);
  assert.doesNotMatch(js, /confirmDecomposition/);
  assert.doesNotMatch(js, /confirmReferenceBtn/);
  assert.match(js, /\/confirm-plan/);
  assert.match(js, /wzv2-confirm-/);
  assert.match(js, /confirmedPlanIds/);
  assert.match(js, /draftSignature:\s*state\.draftSignature/);
  assert.match(js, /clientPlanDraftSignature/);
  assert.match(js, /isBatchQcRunnable/);
  assert.match(js, /\/stop/);
  assert.match(js, /\/qc/);
  assert.match(js, /startBatchPolling/);
  assert.match(js, /DECOMPOSITION_LLM_TIMEOUT_MS\s*=\s*180_000/);
  assert.match(js, /function decompositionJobTimeoutWindowMs\(model = selectedDecompositionModel\(\)\)/);
  assert.match(js, /const maxRetries = decompositionMaxRetries\(model\)/);
  assert.match(js, /markBackgroundJobTimeout/);
  assert.match(js, /markBackgroundJobPollFailure/);
  assert.match(js, /job_poll_timeout/);
  assert.match(js, /job_poll_failed/);
  assert.match(js, /重试查询预案结果/);
  assert.match(js, /重试查询拆解结果/);
  assert.match(js, /后台任务可能仍在运行，可重试查询/);
  assert.match(js, /retryBackgroundJobPoll\("plan"\)/);
  assert.match(js, /retryBackgroundJobPoll\("decomposition"\)/);
  assert.match(js, /decompositionEditedFields:\s*new Set\(\)/);
  assert.match(js, /resetDecompositionDraft\(\{\s*clearForm:\s*true\s*\}\)/);
  assert.match(js, /state\.decompositionEditedFields\.clear\(\)/);
  assert.match(js, /state\.decompositionEditedFields\.has\(field\)/);
  assert.match(js, /dataset\?\.decompositionField/);
  assert.match(js, /decompositionForm\.classList\.remove\("empty-line"\)/);
  assert.match(js, /decompositionForm\.classList\.add\("empty-line"\)/);
  assert.match(js, /已回填到页面/);
  assert.match(js, /strongTruthFields/);
  assert.match(js, /function collectTruthRules\(\)/);
  assert.match(js, /truthRules:\s*collectTruthRules\(\)/);
  assert.match(js, /function currencyValue\(\)/);
  assert.match(js, /currencySymbol:\s*currencyValue\(\)/);
  assert.match(js, /function effectiveMaterialDirection\(\)/);
  assert.match(js, /materialDirection:\s*effectiveMaterialDirection\(\)/);
  assert.doesNotMatch(js, /materialDirection:\s*value\(els\.materialDirection\)/);
  assert.match(js, /templateSnapshot:\s*\{\s*draft:\s*\{/);
  assert.match(js, /targetChannels:\s*\[value\(els\.targetChannel\)\s*\|\|\s*"meta_ads"\]/);
  assert.match(js, /targetRegions:\s*\[region\]/);
  assert.match(js, /regions:\s*\[region\]/);
  assert.match(js, /language,\s*\n\s*languages:\s*\[language\]/);
  assert.match(js, /voiceoverStyle:\s*value\(els\.voiceoverStyle\)/);
  assert.match(js, /cta:\s*value\(els\.cta\)/);
  assert.match(js, /ending:\s*value\(els\.ending\)/);
  assert.match(js, /variantPrompt:\s*value\(els\.variantPrompt\)/);
  assert.match(js, /customPrompt:\s*value\(els\.customPrompt\)/);
  assert.match(js, /negativePrompt:\s*value\(els\.negativePrompt\)/);
  assert.match(js, /批次轮询暂时断开，正在重连/);
  assert.match(js, /批次轮询已恢复/);
  assert.match(js, /TERMINAL_BATCH_STATUSES/);
  assert.doesNotMatch(js, /location\.reload\(/);
  assert.match(js, /VISIBLE_LOG_LIMIT\s*=\s*50/);
  assert.match(js, /state\.visibleLogs\.length\s*>\s*VISIBLE_LOG_LIMIT/);
  assert.match(js, /loadOlderLogs/);
  assert.match(js, /RECENT_PAGE_SIZE\s*=\s*5/);
  assert.match(js, /\/api\/wangzhuan\/tasks\?\$\{query\}/);
  assert.match(js, /pageSize:\s*String\(RECENT_PAGE_SIZE\)/);
  assert.match(js, /openRecentResult/);
  assert.match(js, /loadBatchDetail\(id\)/);
  assert.match(js, /restoreV2FromBatchDetail\(detail\)/);
  assert.match(js, /const form = new FormData\(\)/);
  assert.match(js, /form\.append\("file", file, file\.name\)/);
  assert.doesNotMatch(js, /const content = await fileToDataUrl\(file\);\s*const data = await api\("\/api\/wangzhuan\/reference-videos\/check"/);
});

test("wangzhuan v2 restores task-manager backflow links in place", async () => {
  const js = await readText("public/wangzhuan-v2.js");
  assert.match(js, /readWorkbenchRestoreRequest/);
  assert.match(js, /async function restoreWorkbenchFromUrl\(\)/);
  assert.match(js, /async function restoreBackgroundJobFromRequest\(restoreRequest\)/);
  assert.match(js, /const restoreRequest = readWorkbenchRestoreRequest\(\)/);
  assert.match(js, /\/api\/wangzhuan\/batches\/\$\{encodeURIComponent\(batchId\)\}/);
  assert.match(js, /function restoreV2FromBatchDetail\(detail = \{\}\)/);
  assert.match(js, /referenceVideoFromBatch\(batch\)/);
  assert.match(js, /decompositionFromBatch\(batch\)/);
  assert.match(js, /branchDraftsFromBatch\(batch\)/);
  assert.match(js, /renderPlanEditors\(Array\.isArray\(batch\.plans\) \? batch\.plans : \[\]\)/);
  assert.match(js, /已从任务管理恢复批次/);
  assert.match(js, /await restoreBackgroundJobFromRequest\(restoreRequest\)/);
  assert.match(js, /retryBackgroundJobPoll\("plan"\)/);
  assert.match(js, /retryBackgroundJobPoll\("decomposition"\)/);
  assert.match(js, /restoreWorkbenchFromUrl\(\)/);
});

test("wangzhuan v2 page exposes bounded logs and lazy recent result controls", async () => {
  const html = await readText("public/wangzhuan-v2.html");
  assert.match(html, /id="wzLoadOlderLogsBtn"/);
  assert.match(html, /id="wzRecentResults"/);
  assert.match(html, /只加载最近 5 条摘要/);
  assert.match(html, /id="wzRecentPager"/);
  assert.match(html, /id="wzRefreshRecentBtn"/);
});

test("task manager separates final outputs from intermediate outputs", async () => {
  const js = await readText("public/wangzhuan-tasks.js");
  assert.match(js, /function splitOutputGroups\(outputs = \[\]\)/);
  assert.match(js, /function renderOutputStage/);
  assert.match(js, /function renderOutputCards/);
  assert.match(js, /output\.kind === "segment_video" \|\| output\.kind === "segment"/);
  assert.match(js, /"stitched_video"/);
  assert.match(js, /交付结果/);
  assert.match(js, /最终结果尚未生成/);
  assert.match(js, /中间结果/);
  assert.match(js, /不作为最终交付成片/);
});

test("task manager download action starts zip download with visible feedback", async () => {
  const js = await readText("public/wangzhuan-tasks.js");
  assert.match(js, /async function downloadSelectedTask\(\)/);
  assert.match(js, /result = await downloadZip\(\{/);
  assert.match(js, /batchIds:\s*\[state\.selectedId\]/);
  assert.match(js, /remixIds:\s*\[state\.selectedId\]/);
  assert.match(js, /includeSegments:\s*Boolean\(\$\(("#wzTasksIncludeSegments"|\'#wzTasksIncludeSegments\')\)\?\.checked\)/);
  assert.match(js, /showToast\(`已开始下载 \$\{result\?\.fileName \|\| "交付包"\}`/);
});

test("download packages require final media but allow missing auxiliary files", async () => {
  const source = await readText("server/wangzhuan/package.mjs");
  assert.match(source, /async function addStoredFile/);
  assert.match(source, /return true/);
  assert.match(source, /return false/);
  assert.match(source, /const requiredMissingFiles = \[\]/);
  assert.match(source, /if \(!outputAdded\) requiredMissingFiles\.push\(zipPath\)/);
  assert.match(source, /if \(requiredMissingFiles\.length\)/);
  assert.match(source, /交付包缺少最终视频文件/);
  assert.doesNotMatch(source, /if \(missingFiles\.length\) \{\s*\n\s*throw new WangzhuanError\("missing_required_file"/);
});

test("confirming Seedance asset reviews is not blocked by preview stage", async () => {
  const source = await readText("server/wangzhuan/pipeline.mjs");
  const start = source.indexOf("export async function confirmBatchAssets");
  const end = source.indexOf("function cleanConfirmationNotes", start);
  const confirmAssetsBody = start >= 0 && end > start ? source.slice(start, end) : "";

  assert.ok(confirmAssetsBody, "confirmBatchAssets implementation should be present");
  assert.doesNotMatch(confirmAssetsBody, /batch\.status\s*!==\s*"preview_required"/);
  assert.doesNotMatch(confirmAssetsBody, /当前批次不在预案确认阶段/);
  assert.match(confirmAssetsBody, /ensureAssetReviewsApproved/);
  assert.match(confirmAssetsBody, /asset_review_pending/);
});
