import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../../", import.meta.url);

async function readText(path) {
  return readFile(new URL(path, root), "utf8");
}

test("wangzhuan v2 page keeps old page separate and exposes dense workbench regions", async () => {
  const html = await readText("public/wangzhuan-v2.html");
  assert.match(html, /<title>[^<]*网赚素材管线 v2/);
  assert.doesNotMatch(html, /href="\/wangzhuan\.html"/);
  assert.match(html, /href="\/wangzhuan-v2\.html"[\s\S]*网赚素材管线/);
  assert.match(html, /id="wzV2TaskQueue"/);
  assert.match(html, /id="wzSaveDraftBtn"/);
  assert.match(html, /id="wzGlobalError"/);
  assert.match(html, /id="wzLoginModal"/);
  assert.match(html, /后台任务队列/);
  assert.match(html, /关键提醒/);
  assert.match(html, /查看日志/);
  assert.match(html, /运行与结果/);
});

test("wangzhuan v2 page uses required native controls and field labels", async () => {
  const html = await readText("public/wangzhuan-v2.html");
  assert.match(html, /id="wzReferencePreview"/);
  assert.match(html, /参考视频与 AI 拆解/);
  assert.match(html, /拖拽或选择参考视频/);
  assert.match(html, /<input id="wzProjectName" type="hidden"/);
  assert.doesNotMatch(html, /当前项目/);
  assert.doesNotMatch(html, /上传 Seedance 素材并审核/);
  assert.doesNotMatch(html, /id="wzConfirmAssetsBtn"/);
  assert.match(html, /id="wzAddBranchBtn"/);
  assert.match(html, /id="wzBranchTabs"/);
  assert.match(html, /\+ 裂变子节点/);
  assert.match(html, /<select id="wzTargetRegion">/);
  assert.doesNotMatch(html, /id="wzTargetRegions"[^>]*multiple/);
  assert.match(html, /<select id="wzLanguage">/);
  assert.doesNotMatch(html, /id="wzLanguages"[^>]*multiple/);
  assert.match(html, /<select id="wzCurrencySymbol">/);
  assert.match(html, /<option value="R\$">R\$ BRL<\/option>/);
  assert.match(html, /<option value="MX\$">MX\$ MXN<\/option>/);
  assert.match(html, /<option value="custom">自定义<\/option>/);
  assert.match(html, /id="wzCurrencyCustom"/);
  assert.match(html, /id="wzTruthDetails"/);
  assert.match(html, /强承诺真实规则/);
  assert.match(html, /id="wzTruthFields"/);
  assert.doesNotMatch(html, /id="wzInspectStoreBtn"/);
  assert.doesNotMatch(html, /读取商店页/);
  assert.match(html, /免责声明贴片模板/);
  assert.match(html, /id="wzDisclaimerOverlayFile"/);
  assert.match(html, /id="wzDisclaimerOverlayPreview"/);
  assert.match(html, /id="wzDisclaimerOverlayPosition"/);
  assert.match(html, /id="wzDisclaimerOverlayBoxHeight"/);
  assert.match(html, /id="wzDisclaimerOverlayBottomMargin"/);
  assert.match(html, /id="wzDisclaimerOverlayHorizontalMargin"/);
  assert.doesNotMatch(html, /id="wzDisclaimer"/);
  assert.doesNotMatch(html, /免责声明文案/);
  assert.doesNotMatch(html, /id="wzDisclaimerOverlayFontSize"/);
  assert.doesNotMatch(html, /bottom_left/);
  assert.match(html, /id="wzDeleteTemplateBtn"/);
  assert.match(html, /脚本裂变规则补充/);
  assert.match(html, /<summary>Seedance prompt 提示补充<\/summary>/);
  assert.doesNotMatch(html, /<summary>提示词规则<\/summary>/);
  assert.doesNotMatch(html, /变体数 \* 同时生成数量 \* 3min/);
  assert.match(html, /id="wzLlmModel"/);
  assert.match(html, /id="wzPlanLlmModel"/);
  assert.match(html, /id="wzConfirmLimits"/);
  assert.match(html, /裂变数量[\s\S]*id="wzVariantCount" type="number" min="1" max="10"/);
  assert.match(html, /id="wzSeedanceModel" type="hidden" value="dreamina-seedance-2-0-fast-260128"/);
  assert.match(html, /<select id="wzModelSelect">[\s\S]*dreamina-seedance-2-0-260128[\s\S]*dreamina-seedance-2-0-fast-260128[\s\S]*dreamina-seedance-2-0-mini-260615/);
  assert.match(html, /产品 Logo（最多 9 个）[\s\S]*id="wzProductIconFile"[^>]*multiple/);
  assert.match(html, /产品截图（最多 9 个）[\s\S]*id="wzProductScreenshotFile"[^>]*multiple/);
  assert.match(html, /产品录屏（最多 2 个）[\s\S]*id="wzProductRecordingFile"[^>]*multiple/);
  assert.match(html, /Seedance prompt/);
  assert.doesNotMatch(html, /Seedance 预案/);
  assert.doesNotMatch(html, /id="wzEstimateBtn"/);
  assert.doesNotMatch(html, /估算本批任务/);
  assert.match(html, /<div class="wz-v2-section-head">[\s\S]*id="wzConfirmPlanBtn"[\s\S]*确认 prompt 并生成视频[\s\S]*<\/div>/);
  assert.match(html, /<option value="gemini-3\.1-pro-preview">Gemini 3\.1 Pro Preview<\/option>/);
  assert.match(html, /id="wzGeminiDecompositionHint"[\s\S]*视频拆解通常需要 1-3 分钟/);
  assert.match(html, /<select id="wzLlmModel">[\s\S]*<option value="gpt-5\.5" selected>GPT-5\.5<\/option>/);
  assert.match(html, /<select id="wzPlanLlmModel">[\s\S]*<option value="gpt-5\.5" selected>GPT-5\.5<\/option>/);
  assert.doesNotMatch(html, /<option value="gemini-3\.5-flash"/);
  assert.doesNotMatch(html, /Gemini 3\.5 Flash/);
  assert.doesNotMatch(html, /id="wzDecomposeBtn"/);
  assert.doesNotMatch(html, /确认脚本拆解/);
  assert.doesNotMatch(html, /id="wzConfirmReferenceBtn"/);
  assert.doesNotMatch(html, /确认进入脚本拆解/);
});

test("wangzhuan v2 script submits array-compatible selects and uses background jobs", async () => {
  const js = await readText("public/wangzhuan-v2.js");
  assert.match(js, /targetRegions:\s*\[region\]/);
  assert.match(js, /languages:\s*\[language\]/);
  assert.match(js, /\/api\/wangzhuan\/reference-videos\/decomposition-jobs/);
  assert.match(js, /\/api\/wangzhuan\/batches\/plan-jobs/);
  assert.match(js, /const GEMINI_DECOMPOSITION_TIMEOUT_MS = 300_000/);
  assert.match(js, /function syncGeminiDecompositionHint\(\)/);
  assert.match(js, /startsWith\("gemini-"\)/);
  assert.match(js, /timeoutMs = decompositionTimeoutMs\(model\)/);
  assert.match(js, /Gemini 视频拆解可能持续数分钟/);
  assert.match(js, /els\.draftDecompositionBtn\.disabled = hasGeneratedSeedancePlan\(\)/);
  assert.match(js, /如需调整，可重新拆解/);
  assert.match(js, /PLAN_UPSTREAM_LOCK_SELECTOR/);
  assert.match(js, /function hasGeneratedSeedancePlan/);
  assert.match(js, /\["queued", "running", "stitching", "qc", "partial_failed", "succeeded", "failed", "stopped", "skipped"\]/);
  assert.match(js, /function setPlanUpstreamLocked\(locked\)/);
  assert.match(js, /setPlanUpstreamLocked\(planUpstreamLocked\)/);
  assert.match(js, /const planRetryable = isRecoverableBackgroundJob\(state\.planJob\)/);
  assert.match(js, /const planDisabled = planRetryable/);
  assert.match(js, /els\.planBatchBtn\.disabled = planDisabled/);
  assert.match(js, /const planBlockedByRewrite = !state\.rewriteConfirmed/);
  assert.match(js, /const planBlockedByDecomposition = !decompositionReady/);
  assert.match(js, /视频拆解进行中；拆解完成或手动填写脚本拆解后，可直接生成 Seedance prompt/);
  assert.match(js, /请先确认产品\/投放信息/);
  assert.doesNotMatch(js, /estimateBtn:/);
  assert.doesNotMatch(js, /wzEstimateBtn/);
  assert.match(js, /els\.confirmPlanBtn\.disabled = state\.confirmPlanSubmitting \|\| !plans\.length/);
  assert.match(js, /state\.confirmPlanSubmitting = true/);
  assert.match(js, /log\("正在确认 prompt 并提交 Seedance\.\.\."\)/);
  assert.match(js, /setBusy\(els\.confirmPlanBtn, true, "提交中"\)/);
  assert.match(js, /state\.batchDetail = data\.batch \? data : \{ batch: data\.confirmedBatch \|\| batch \};\s*\n\s*log\("Seedance prompt 已确认，已提交 Seedance 生成"\);\s*\n\s*renderTasks\(\);/);
  assert.match(js, /finally \{\s*\n\s*state\.confirmPlanSubmitting = false/);
  assert.match(js, /setPlanUpstreamLocked\(true\)/);
  assert.match(js, /if \(type === "plan"\) setPlanUpstreamLocked\(false\)/);
  assert.match(js, /setPlanUpstreamLocked\(false\);\s*\n\s*state\.referenceVideo = null/);
  assert.match(js, /draftSignatureInput/);
  assert.match(js, /stalePlanPreview/);
  assert.match(js, /wzPlanStaleNotice/);
  assert.match(js, /ensureBatchName\(\)/);
  assert.match(js, /function collectBranchDrafts\(\)/);
  assert.match(js, /branchDrafts:\s*estimateRequest\(\)\.branches/);
  assert.match(js, /const branches = collectBranchDrafts\(\)/);
  assert.match(js, /\/api\/wangzhuan\/product-assets\/upload/);
  assert.match(js, /referenceVideoId:\s*source\.referenceVideoId \|\| state\.decompositionDraft\?\.referenceVideoId \|\| state\.referenceVideo\?\.referenceVideoId/);
  assert.match(js, /schemaVersion:\s*source\.schemaVersion \|\| state\.decompositionDraft\?\.schemaVersion \|\| "video_decomposition\.v1"/);
  assert.match(js, /assertSeedanceReferenceAssetLimit\(\);\s*\n\s*await saveDraft\("estimate"\)/);
  assert.match(js, /await saveDraft\("estimate"\)/);
  assert.match(js, /els\.planBatchBtn\.disabled = true;\s*\n\s*assertSeedanceReferenceAssetLimit\(\);/);
  assert.match(js, /const estimateResult = state\.estimate\?\.estimateId \? state\.estimate : await estimateBatch\(\)/);
  assert.match(js, /estimateId:\s*estimateResult\.estimateId/);
  assert.match(js, /decomposition:\s*currentDecomposition\(\)/);
  assert.match(js, /const DEFAULT_SEEDANCE_MODEL = "dreamina-seedance-2-0-fast-260128"/);
  assert.match(js, /function normalizeSeedanceModel\(model = ""\)/);
  assert.match(js, /if \(!valueText\) return DEFAULT_SEEDANCE_MODEL/);
  assert.doesNotMatch(js, /valueText === "dreamina-seedance-2-0-260128"/);
  assert.match(js, /function isAssetReviewApproved\(status = ""\)/);
  assert.match(js, /\["approved", "active", "success", "succeeded", "pass", "passed"\]/);
  assert.match(js, /!isAssetReviewApproved\(review\.status\)/);
  assert.match(js, /MULTI_ASSET_LIMITS/);
  assert.match(js, /productIcon:\s*9/);
  assert.match(js, /productScreenshot:\s*9/);
  assert.match(js, /productRecording:\s*2/);
  assert.match(js, /function validateAssetInputLimit/);
  assert.match(js, /function countSeedanceReferenceAssets/);
  assert.match(js, /function assertSeedanceReferenceAssetLimit/);
  assert.match(js, /Seedance 参考素材不能超过 9 个，请减少后重试/);
  assert.match(js, /requestId: /);
  assert.match(js, /function taskFailureHint/);
  assert.match(js, /function logTaskFailureDetails/);
  assert.match(js, /continuity_reference_failed/);
  assert.match(js, /function deleteSelectedTemplate/);
  assert.match(js, /\/api\/wangzhuan\/templates\/admin/);
  assert.match(js, /action:\s*"delete"/);
  assert.match(js, /\/confirm-assets/);
  assert.match(js, /\/api\/wangzhuan\/batches\/draft/);
  assert.match(js, /function currentBatchId\(\)/);
  assert.match(js, /batchId:\s*currentBatchId\(\)\s*\|\|\s*undefined/);
  assert.match(js, /referenceVideo:\s*state\.referenceVideo/);
  assert.match(js, /branchDrafts:\s*estimateRequest\(\)\.branches/);
  assert.match(js, /\/api\/auth/);
  assert.match(js, /\/api\/login/);
  assert.match(js, /loadTemplates/);
  assert.match(js, /applyTemplate/);
  assert.match(js, /variantPrompt:\s*value\(els\.variantPrompt\)/);
  assert.match(js, /customPrompt:\s*value\(els\.customPrompt\)/);
  assert.match(js, /negativePrompt:\s*value\(els\.negativePrompt\)/);
  assert.match(js, /variantPrompt:\s*branch\.variantPrompt \|\| draft\.variantPrompt \|\| ""/);
  assert.match(js, /customPrompt:\s*branch\.customPrompt \|\| draft\.customPrompt \|\| ""/);
  assert.match(js, /negativePrompt:\s*branch\.negativePrompt \|\| draft\.negativePrompt \|\| ""/);
  assert.match(js, /confirmRewriteInfo/);
  assert.match(js, /产品\/投放信息已确认，视频拆解尚未完成；拆解完成后可直接生成 Seedance prompt/);
  assert.match(js, /renderPlanEditors/);
  assert.match(js, /renderReminders/);
  assert.match(js, /产品信息已确认，等待视频拆解完成后可直接生成 Seedance prompt/);
  assert.match(js, /disclaimerRequestFields/);
  assert.match(js, /function currentDecomposition\(\)/);
  assert.match(js, /decomposition:\s*currentDecomposition\(\)/);
  assert.doesNotMatch(js, /\/api\/wangzhuan\/reference-videos\/decompose/);
  assert.doesNotMatch(js, /wzv2-decompose-/);
  assert.doesNotMatch(js, /confirmDecomposition/);
  assert.doesNotMatch(js, /confirmReferenceBtn/);
  assert.match(js, /\/confirm-plan/);
  assert.match(js, /wzv2-confirm-/);
  assert.match(js, /confirmedPlanIds/);
  assert.match(js, /draftSignature:\s*state\.draftSignature/);
  assert.match(js, /clientPlanDraftSignature/);
  assert.match(js, /isBatchQcRunnable/);
  assert.match(js, /\/stop/);
  assert.match(js, /\/qc/);
  assert.match(js, /startBatchPolling/);
  assert.match(js, /DECOMPOSITION_LLM_TIMEOUT_MS\s*=\s*180_000/);
  assert.match(js, /function decompositionJobTimeoutWindowMs\(model = selectedDecompositionModel\(\)\)/);
  assert.match(js, /const maxRetries = decompositionMaxRetries\(model\)/);
  assert.match(js, /markBackgroundJobTimeout/);
  assert.match(js, /markBackgroundJobPollFailure/);
  assert.match(js, /job_poll_timeout/);
  assert.match(js, /job_poll_failed/);
  assert.match(js, /重试查询 prompt 结果/);
  assert.match(js, /重试查询拆解结果/);
  assert.match(js, /后台任务可能仍在运行，可重试查询/);
  assert.match(js, /retryBackgroundJobPoll\("plan"\)/);
  assert.match(js, /retryBackgroundJobPoll\("decomposition"\)/);
  assert.match(js, /decompositionEditedFields:\s*new Set\(\)/);
  assert.match(js, /resetDecompositionDraft\(\{\s*clearForm:\s*true\s*\}\)/);
  assert.match(js, /state\.decompositionEditedFields\.clear\(\)/);
  assert.match(js, /state\.decompositionEditedFields\.has\(field\)/);
  assert.match(js, /dataset\?\.decompositionField/);
  assert.match(js, /decompositionForm\.classList\.remove\("empty-line"\)/);
  assert.match(js, /decompositionForm\.classList\.add\("empty-line"\)/);
  assert.match(js, /已回填到页面/);
  assert.match(js, /strongTruthFields/);
  assert.match(js, /function collectTruthRules\(\)/);
  assert.match(js, /truthRules:\s*collectTruthRules\(\)/);
  assert.match(js, /function currencyValue\(\)/);
  assert.match(js, /currencySymbol:\s*currencyValue\(\)/);
  assert.match(js, /function effectiveMaterialDirection\(\)/);
  assert.match(js, /materialDirection:\s*effectiveMaterialDirection\(\)/);
  assert.doesNotMatch(js, /materialDirection:\s*value\(els\.materialDirection\)/);
  assert.match(js, /templateSnapshot:\s*\{\s*draft:\s*\{/);
  assert.match(js, /targetChannels:\s*\[value\(els\.targetChannel\)\s*\|\|\s*"meta_ads"\]/);
  assert.match(js, /targetRegions:\s*\[region\]/);
  assert.match(js, /regions:\s*\[region\]/);
  assert.match(js, /language,\s*\n\s*languages:\s*\[language\]/);
  assert.match(js, /voiceoverStyle:\s*value\(els\.voiceoverStyle\)/);
  assert.match(js, /cta:\s*value\(els\.cta\)/);
  assert.match(js, /ending:\s*value\(els\.ending\)/);
  assert.match(js, /variantPrompt:\s*value\(els\.variantPrompt\)/);
  assert.match(js, /customPrompt:\s*value\(els\.customPrompt\)/);
  assert.match(js, /negativePrompt:\s*value\(els\.negativePrompt\)/);
  assert.match(js, /批次轮询暂时断开，正在重连/);
  assert.match(js, /批次轮询已恢复/);
  assert.match(js, /TERMINAL_BATCH_STATUSES/);
  assert.doesNotMatch(js, /location\.reload\(/);
  assert.match(js, /VISIBLE_LOG_LIMIT\s*=\s*50/);
  assert.match(js, /state\.visibleLogs\.length\s*>\s*VISIBLE_LOG_LIMIT/);
  assert.match(js, /loadOlderLogs/);
  assert.match(js, /RECENT_PAGE_SIZE\s*=\s*5/);
  assert.match(js, /\/api\/wangzhuan\/tasks\?\$\{query\}/);
  assert.match(js, /pageSize:\s*String\(RECENT_PAGE_SIZE\)/);
  assert.match(js, /openRecentResult/);
  assert.match(js, /loadBatchDetail\(id\)/);
  assert.match(js, /restoreV2FromBatchDetail\(detail\)/);
  assert.match(js, /const form = new FormData\(\)/);
  assert.match(js, /form\.append\("file", file, file\.name\)/);
  assert.doesNotMatch(js, /const content = await fileToDataUrl\(file\);\s*const data = await api\("\/api\/wangzhuan\/reference-videos\/check"/);
});

test("v2 captures wangzhuan output template fields for Seedance planning", async () => {
  const html = await readFile(new URL("../../public/wangzhuan-v2.html", import.meta.url), "utf8");
  const js = await readFile(new URL("../../public/wangzhuan-v2.js", import.meta.url), "utf8");
  const jobs = await readFile(new URL("../../server/wangzhuan/background-jobs.mjs", import.meta.url), "utf8");

  assert.match(html, /id="wzOutputTemplateMode"/);
  assert.match(html, /三段式拼接/);
  assert.match(html, /短剧高光 \+ 赚钱安利/);
  assert.match(html, /id="wzSliceStrategy"/);
  assert.match(html, /id="wzMoneyVisuals"/);
  assert.match(html, /id="wzSubtitleWorkflow"/);

  assert.match(js, /outputTemplateMode:\s*value\(els\.outputTemplateMode\)/);
  assert.match(js, /sliceStrategy:\s*value\(els\.sliceStrategy\)/);
  assert.match(js, /moneyVisuals:\s*selectedValues\(els\.moneyVisuals\)/);
  assert.match(js, /subtitleWorkflow:\s*value\(els\.subtitleWorkflow\)/);
  assert.match(js, /const signatureFields = \[[\s\S]*"outputTemplateMode"[\s\S]*"sliceStrategy"[\s\S]*"moneyVisuals"[\s\S]*"subtitleWorkflow"[\s\S]*"branches"[\s\S]*\]/);
  assert.match(js, /function currentDraft\(\)[\s\S]*const active = branches\[state\.activeBranchIndex\] \|\| primary/);
  assert.match(js, /function currentDraft\(\)[\s\S]*outputTemplateMode:\s*active\.outputTemplateMode \|\| value\(els\.outputTemplateMode\)/);
  assert.match(js, /function currentDraft\(\)[\s\S]*sliceStrategy:\s*active\.sliceStrategy \|\| value\(els\.sliceStrategy\)/);
  assert.match(js, /function currentDraft\(\)[\s\S]*moneyVisuals:\s*active\.moneyVisuals \|\| selectedValues\(els\.moneyVisuals\)/);
  assert.match(js, /function currentDraft\(\)[\s\S]*subtitleWorkflow:\s*active\.subtitleWorkflow \|\| value\(els\.subtitleWorkflow\)/);
  assert.match(js, /function planSignatureInput\(\)[\s\S]*const active = branches\[state\.activeBranchIndex\] \|\| branches\[0\] \|\| \{\}/);
  assert.match(js, /function planSignatureInput\(\)[\s\S]*outputTemplateMode:\s*active\.outputTemplateMode \|\| value\(els\.outputTemplateMode\)/);
  assert.match(js, /function planSignatureInput\(\)[\s\S]*sliceStrategy:\s*active\.sliceStrategy \|\| value\(els\.sliceStrategy\)/);
  assert.match(js, /function planSignatureInput\(\)[\s\S]*moneyVisuals:\s*active\.moneyVisuals \|\| selectedValues\(els\.moneyVisuals\)/);
  assert.match(js, /function planSignatureInput\(\)[\s\S]*subtitleWorkflow:\s*active\.subtitleWorkflow \|\| value\(els\.subtitleWorkflow\)/);
  assert.match(js, /function planSignatureInput\(\)[\s\S]*branches\s*\n\s*\}/);
  assert.match(js, /function estimateRequest\(\)[\s\S]*const active = branches\[state\.activeBranchIndex\] \|\| branches\[0\] \|\| \{\}/);
  assert.match(js, /function estimateRequest\(\)[\s\S]*outputTemplateMode:\s*active\.outputTemplateMode \|\| value\(els\.outputTemplateMode\)/);
  assert.match(js, /function estimateRequest\(\)[\s\S]*sliceStrategy:\s*active\.sliceStrategy \|\| value\(els\.sliceStrategy\)/);
  assert.match(js, /function estimateRequest\(\)[\s\S]*moneyVisuals:\s*active\.moneyVisuals \|\| selectedValues\(els\.moneyVisuals\)/);
  assert.match(js, /function estimateRequest\(\)[\s\S]*subtitleWorkflow:\s*active\.subtitleWorkflow \|\| value\(els\.subtitleWorkflow\)/);
  assert.doesNotMatch(js, /outputTemplateMode:\s*primary\.outputTemplateMode/);
  assert.doesNotMatch(js, /sliceStrategy:\s*primary\.sliceStrategy/);
  assert.doesNotMatch(js, /moneyVisuals:\s*primary\.moneyVisuals/);
  assert.doesNotMatch(js, /subtitleWorkflow:\s*primary\.subtitleWorkflow/);
  assert.match(js, /function addBranch\(\)[\s\S]*outputTemplateMode:\s*source\.outputTemplateMode/);
  assert.match(js, /function addBranch\(\)[\s\S]*sliceStrategy:\s*source\.sliceStrategy/);
  assert.match(js, /function addBranch\(\)[\s\S]*moneyVisuals:\s*source\.moneyVisuals/);
  assert.match(js, /function addBranch\(\)[\s\S]*subtitleWorkflow:\s*source\.subtitleWorkflow/);
  assert.match(js, /for \(const el of \[[\s\S]*els\.outputTemplateMode[\s\S]*els\.sliceStrategy[\s\S]*els\.moneyVisuals[\s\S]*els\.subtitleWorkflow[\s\S]*\]\) \{\s*el\?\.addEventListener\("change", markPlanMaybeStale\);\s*el\?\.addEventListener\("input", markPlanMaybeStale\);/);

  assert.match(jobs, /"outputTemplateMode"/);
  assert.match(jobs, /"sliceStrategy"/);
  assert.match(jobs, /"moneyVisuals"/);
  assert.match(jobs, /"subtitleWorkflow"/);
  assert.match(jobs, /const PLAN_SIGNATURE_FIELDS = Object\.freeze\(\[[\s\S]*"outputTemplateMode"[\s\S]*"sliceStrategy"[\s\S]*"moneyVisuals"[\s\S]*"subtitleWorkflow"[\s\S]*"branches"[\s\S]*\]\)/);
});

test("v2 plan editor exposes output-template plan fields", async () => {
  const js = await readFile(new URL("../../public/wangzhuan-v2.js", import.meta.url), "utf8");
  const pipeline = await readFile(new URL("../../server/wangzhuan/pipeline.mjs", import.meta.url), "utf8");

  assert.match(js, /data-plan-field="body"/);
  assert.match(js, /data-plan-field="imagePrompt"/);
  assert.match(js, /data-plan-field="subtitles"/);
  assert.match(js, /data-plan-field="cta"/);
  assert.match(js, /data-plan-field="ending"/);
  assert.match(js, /data-plan-field="moneyVisuals"/);
  assert.match(js, /data-plan-field="withdrawalVisual"/);
  assert.match(js, /data-plan-field="subtitleScript"/);
  assert.match(js, /readList\("moneyVisuals"\)/);
  assert.match(js, /const text = fieldValue\(field\);\s*\n\s*return text === undefined \? undefined : splitLines\(text\);/);
  assert.match(js, /subtitles:\s*subtitles \?\? plan\.subtitles/);
  assert.match(js, /moneyVisuals:\s*moneyVisuals \?\? plan\.moneyVisuals/);
  assert.match(js, /subtitleScript:\s*subtitleScript \?\? \(plan\.subtitleWorkflow\?\.subtitleScript \|\| plan\.subtitles \|\| \[\]\)/);
  assert.doesNotMatch(js, /subtitles:\s*subtitles\.length \? subtitles : plan\.subtitles/);
  assert.doesNotMatch(js, /moneyVisuals:\s*moneyVisuals\.length \? moneyVisuals : plan\.moneyVisuals/);
  assert.doesNotMatch(js, /subtitleScript:\s*subtitleScript\.length \? subtitleScript :/);
  assert.match(js, /subtitleWorkflow:\s*\{/);
  assert.match(pipeline, /buildGenerationPlanRecord\([\s\S]*planPayload:\s*\{[\s\S]*segmentRole[\s\S]*sliceDurationSec[\s\S]*outputTemplateMode[\s\S]*moneyVisuals[\s\S]*withdrawalVisual[\s\S]*subtitleWorkflow[\s\S]*sliceDiversity/);
  assert.match(pipeline, /const nextScript = \{[\s\S]*segmentRole:\s*plan\.segmentRole[\s\S]*sliceDurationSec:\s*plan\.sliceDurationSec[\s\S]*outputTemplateMode:\s*plan\.outputTemplateMode[\s\S]*moneyVisuals:\s*plan\.moneyVisuals[\s\S]*withdrawalVisual:\s*plan\.withdrawalVisual[\s\S]*subtitleWorkflow:\s*plan\.subtitleWorkflow[\s\S]*sliceDiversity:\s*plan\.sliceDiversity/);
});

test("wangzhuan v2 restores task-manager backflow links in place", async () => {
  const js = await readText("public/wangzhuan-v2.js");
  assert.match(js, /readWorkbenchRestoreRequest/);
  assert.match(js, /async function restoreWorkbenchFromUrl\(\)/);
  assert.match(js, /async function restoreBackgroundJobFromRequest\(restoreRequest\)/);
  assert.match(js, /const restoreRequest = readWorkbenchRestoreRequest\(\)/);
  assert.match(js, /\/api\/wangzhuan\/batches\/\$\{encodeURIComponent\(batchId\)\}/);
  assert.match(js, /function restoreV2FromBatchDetail\(detail = \{\}\)/);
  assert.match(js, /referenceVideoFromBatch\(batch\)/);
  assert.match(js, /decompositionFromBatch\(batch\)/);
  assert.match(js, /branchDraftsFromBatch\(batch\)/);
  assert.match(js, /renderPlanEditors\(Array\.isArray\(batch\.plans\) \? batch\.plans : \[\]\)/);
  assert.match(js, /已从任务管理恢复批次/);
  assert.match(js, /await restoreBackgroundJobFromRequest\(restoreRequest\)/);
  assert.match(js, /retryBackgroundJobPoll\("plan"\)/);
  assert.match(js, /retryBackgroundJobPoll\("decomposition"\)/);
  assert.match(js, /restoreWorkbenchFromUrl\(\)/);
});

test("wangzhuan v2 page exposes bounded logs and lazy recent result controls", async () => {
  const html = await readText("public/wangzhuan-v2.html");
  assert.match(html, /id="wzLoadOlderLogsBtn"/);
  assert.match(html, /id="wzRecentResults"/);
  assert.match(html, /只加载最近 5 条摘要/);
  assert.match(html, /id="wzRecentPager"/);
  assert.match(html, /id="wzRefreshRecentBtn"/);
});

test("task manager separates final outputs from intermediate outputs", async () => {
  const js = await readText("public/wangzhuan-tasks.js");
  assert.match(js, /function batchWorkflowStep\(batch = \{\}\)/);
  assert.match(js, /1 上传视频并拆解/);
  assert.match(js, /2 产品改写信息填写/);
  assert.match(js, /3 生成 Seedance 提示词/);
  assert.match(js, /4 生成视频和质检/);
  assert.match(js, /5 结果确认和下载/);
  assert.match(js, /function taskWorkflowStripe\(item = \{\}\)/);
  assert.match(js, /function batchWorkflowBadge\(batch = \{\}\)/);
  assert.match(js, /taskWorkflowStripe\(item\)/);
  assert.match(js, /batchWorkflowBadge\(batch\)/);
  assert.match(js, /function splitOutputGroups\(outputs = \[\], options = \{\}\)/);
  assert.match(js, /expectedDurationSec/);
  assert.match(js, /function renderOutputStage/);
  assert.match(js, /function renderOutputCards/);
  assert.match(js, /function renderSourceMediaStage/);
  assert.match(js, /renderSourceMediaStage\(\{/);
  const batchDetailBody = js.slice(js.indexOf("function renderBatchDetail"), js.indexOf("function renderRemixDetail"));
  const remixDetailBody = js.slice(js.indexOf("function renderRemixDetail"), js.indexOf("function shouldPollDetail"));
  assert.doesNotMatch(batchDetailBody, /renderTaskMediaCompare/);
  assert.doesNotMatch(remixDetailBody, /renderTaskMediaCompare/);
  assert.match(js, /class="wzTasksOutputCheckbox"/);
  assert.match(js, /function selectedOutputIds\(\)/);
  assert.match(js, /function qcBadge\(output = \{\}\)/);
  assert.match(js, /QC 通过/);
  assert.match(js, /QC 未通过/);
  assert.match(js, /function isDeliveryOutput\(output = \{\}\)/);
  assert.match(js, /function hasStitchedDeliveryOutput\(outputs = \[\]\)/);
  assert.match(js, /context\.hasStitchedOutput/);
  assert.match(js, /\["stitched_video", "remix_video"\]/);
  assert.match(js, /"stitched_video"/);
  assert.match(js, /交付结果/);
  assert.match(js, /包含 QC 通过、警告、未通过和未质检状态/);
  assert.match(js, /最终结果尚未生成/);
  assert.match(js, /中间结果/);
  assert.match(js, /Seedance 生成的分段或处理过程视频/);
});

test("task manager download action starts zip download with visible feedback", async () => {
  const js = await readText("public/wangzhuan-tasks.js");
  assert.match(js, /async function downloadSelectedTask\(\)/);
  assert.match(js, /result = await downloadZip\(\{/);
  assert.match(js, /batchIds:\s*\[state\.selectedId\]/);
  assert.match(js, /remixIds:\s*\[state\.selectedId\]/);
  assert.match(js, /const outputIds = selectedOutputIds\(\)/);
  assert.match(js, /outputIds,/);
  assert.match(js, /remixOutputIds:\s*outputIds/);
  assert.match(js, /请先勾选要下载的视频/);
  assert.match(js, /下载选中视频/);
  assert.doesNotMatch(js, /wzTasksIncludeSegments/);
  assert.match(js, /showToast\(`已开始下载 \$\{result\?\.fileName \|\| "选中视频"\}`/);
});

test("download packages require final media but allow missing auxiliary files", async () => {
  const source = await readText("server/wangzhuan/package.mjs");
  assert.match(source, /async function addStoredFile/);
  assert.match(source, /return true/);
  assert.match(source, /return false/);
  assert.match(source, /const requiredMissingFiles = \[\]/);
  assert.match(source, /if \(!outputAdded\) requiredMissingFiles\.push\(zipPath\)/);
  assert.match(source, /if \(requiredMissingFiles\.length\)/);
  assert.match(source, /交付包缺少最终视频文件/);
  assert.doesNotMatch(source, /if \(missingFiles\.length\) \{\s*\n\s*throw new WangzhuanError\("missing_required_file"/);
});

test("download packages support selected-output-only video zips", async () => {
  const source = await readText("server/wangzhuan/package.mjs");
  assert.match(source, /function normalizeIdSet\(values\)/);
  assert.match(source, /function hasSelectedOutputFilter\(request\)/);
  assert.match(source, /const selectedOutputIds = normalizeIdSet\(request\.outputIds\)/);
  assert.match(source, /normalizeIdSet\(request\.remixOutputIds\)/);
  assert.match(source, /const selectedOnly = hasSelectedOutputFilter\(request\)/);
  assert.match(source, /if \(selectedOnly\) \{/);
  assert.match(source, /if \(!selectedOnly\) addStringFile\(files, "package-manifest\.json", manifest\)/);
});

test("confirming Seedance asset reviews is not blocked by preview stage", async () => {
  const source = await readText("server/wangzhuan/pipeline.mjs");
  const start = source.indexOf("export async function confirmBatchAssets");
  const end = source.indexOf("function cleanConfirmationNotes", start);
  const confirmAssetsBody = start >= 0 && end > start ? source.slice(start, end) : "";

  assert.ok(confirmAssetsBody, "confirmBatchAssets implementation should be present");
  assert.doesNotMatch(confirmAssetsBody, /batch\.status\s*!==\s*"preview_required"/);
  assert.doesNotMatch(confirmAssetsBody, /当前批次不在预案确认阶段/);
  assert.match(confirmAssetsBody, /ensureAssetReviewsApproved/);
  assert.match(confirmAssetsBody, /asset_review_pending/);
});
