-- Local/test rollback for 0001_mysql_foundation.
-- Production rollback should be a new forward migration after impact review.

DROP TABLE IF EXISTS telemetry_events;
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS resource_locks;
DROP TABLE IF EXISTS state_transition_events;
DROP TABLE IF EXISTS state_transition_rules;
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS download_package_items;
DROP TABLE IF EXISTS download_packages;
DROP TABLE IF EXISTS remix_regions;
DROP TABLE IF EXISTS stitch_reports;
DROP TABLE IF EXISTS qc_reports;
DROP TABLE IF EXISTS workflow_outputs;
DROP TABLE IF EXISTS scheduler_jobs;
DROP TABLE IF EXISTS task_attempts;
DROP TABLE IF EXISTS workflow_tasks;
DROP TABLE IF EXISTS generation_scripts;
DROP TABLE IF EXISTS workflow_runs;
DROP TABLE IF EXISTS work_estimates;
DROP TABLE IF EXISTS video_decompositions;
DROP TABLE IF EXISTS reference_videos;
DROP TABLE IF EXISTS channel_rules;
DROP TABLE IF EXISTS project_default_template_versions;
DROP TABLE IF EXISTS product_template_versions;
DROP TABLE IF EXISTS product_templates;
DROP TABLE IF EXISTS asset_files;
DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS rbac_role_permissions;
DROP TABLE IF EXISTS rbac_permissions;
DROP TABLE IF EXISTS rbac_roles;
DROP TABLE IF EXISTS auth_login_attempts;
DROP TABLE IF EXISTS auth_sessions;
DROP TABLE IF EXISTS app_users;
DROP TABLE IF EXISTS app_schema_migrations;
