ALTER TABLE workflow_outputs
  DROP CHECK ck_workflow_outputs_kind;

ALTER TABLE workflow_outputs
  ADD CONSTRAINT ck_workflow_outputs_kind
  CHECK (output_kind IN ('segment_video', 'stitched_video', 'expanded_video', 'stitch_failed', 'remix_video', 'image'));

INSERT INTO app_schema_migrations (version, description)
VALUES ('0016_expanded_video_output_kind', 'Allow expanded video workflow outputs generated by post-processing')
ON DUPLICATE KEY UPDATE applied_at = applied_at;
